/***************************************************************
This code was generated by  Spiral 6.0 beta, www.spiral.net --
Copyright (c) 2005, Carnegie Mellon University
All rights reserved.
The code is distributed under a BSD style license
(see http://www.opensource.org/licenses/bsd-license.php)

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

* Redistributions of source code must retain the above copyright
  notice, reference to Spiral, this list of conditions and the
  following disclaimer.
* Redistributions in binary form must reproduce the above
  copyright notice, this list of conditions and the following
  disclaimer in the documentation and/or other materials provided
  with the distribution.
* Neither the name of Carnegie Mellon University nor the name of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*AS IS* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
******************************************************************/

/*	CPU: Intel Core i7 at 3500 MHz, 4 cores, SSE4_2
	OS: Linux64
	SVN: 99/113 (modified)
	profile: linux-x86, -O2 -Wall -fomit-frame-pointer -mavx -std=c99
	timestamp: Oct 7, 2014; 6:20:26
	transform: TRC(PSInterpolationStage(1, 9, 9, 9)).withTags([ AVecReg(AVX_4x64f) ])
	source file: "opts_cplx_TRC_PSInterpolationStage_1_9_9_9.c(.c)"
	performance: 37243.0 cycles, 0 Mflop/s

algorithm: TRC_cplxvect( TRC(PSInterpolationStage(1, 9, 9, 9)).withTags([ AVecReg(AVX_4x64f) ]),
  @_Base( DPWrapper(PSInterpolationStage(1, 9, 9, 9).withTags([ AVecRegCx(AVX_4x64f) ]), VWrapTRCcplx(AVX_4x64f)),
    PSInterpolationStage_3dv_special( PSInterpolationStage(1, 9, 9, 9).withTags([ AVecRegCx(AVX_4x64f) ]),
      AxI_vec( TTensorI(Scat(L(18, 2)) * 
          VStack(
            I(9), 
            Interp(9)
          ) * 
          Gath(fCompose(L(18, 2), H(18, 9, 0, 1))), 324, AVec, AVec).withTags([ AVecRegCx(AVX_4x64f) ]),
        AxI_base( TTensorI(DPWrapper(Scat(L(18, 2)) * 
              VStack(
                I(9), 
                Interp(9)
              ) * 
              Gath(fCompose(L(18, 2), H(18, 9, 0, 1))), VWrap(AVX_4x64f)), 162, AVec, AVec),
          @_Base( DPWrapper(Scat(L(18, 2)) * 
              VStack(
                I(9), 
                Interp(9)
              ) * 
              Gath(fCompose(L(18, 2), H(18, 9, 0, 1))), VWrap(AVX_4x64f)),
            @_Base( Scat(L(18, 2)) * 
              VStack(
                I(9), 
                Interp(9)
              ) * 
              Gath(fCompose(L(18, 2), H(18, 9, 0, 1))),
              @_Base( Scat(L(18, 2)) ),
              @_Base( VStack(
                  I(9), 
                  Interp(9)
                ),
                @_Base( I(9) ),
                Interp_base( Interp(9),
                  TCompose_tag( TCompose([ DFT(9, 1), TDiag(FData(D629)), DFT(9, 8) ]),
                    DFT_CT( DFT(9, 1),
                      DFT_Rader( DFT(3, 1),
                        DFT_Base( DFT(2, 1) ),
                        DFT_Base( DFT(2, 1) ) ),
                      DFT_Rader( DFT(3, 1),
                        DFT_Base( DFT(2, 1) ),
                        DFT_Base( DFT(2, 1) ) ) ),
                    TDiag_tag( TDiag(FData(D629)) ),
                    DFT_CT( DFT(9, 8),
                      DFT_Rader( DFT(3, 2),
                        DFT_Base( DFT(2, 1) ),
                        DFT_Base( DFT(2, 1) ) ),
                      DFT_Rader( DFT(3, 2),
                        DFT_Base( DFT(2, 1) ),
                        DFT_Base( DFT(2, 1) ) ) ) ) ) ),
              @_Base( Gath(fCompose(L(18, 2), H(18, 9, 0, 1))) ) ) ) ) ),
      PSInterpolationStage_2dv( PSInterpolationStage(2, 1, 9, 9).withTags([ AVecRegCx(AVX_4x64f) ]),
        AxI_vec( TTensorI(Scat(L(18, 2)) * 
            VStack(
              I(9), 
              Interp(9)
            ) * 
            Gath(fCompose(L(18, 2), H(18, 9, 0, 1))), 2, AVec, AVec).withTags([ AVecRegCx(AVX_4x64f) ]),
          @_Base( DPWrapper(Scat(L(18, 2)) * 
              VStack(
                I(9), 
                Interp(9)
              ) * 
              Gath(fCompose(L(18, 2), H(18, 9, 0, 1))), VWrap(AVX_4x64f)),
            @_Base( Scat(L(18, 2)) * 
              VStack(
                I(9), 
                Interp(9)
              ) * 
              Gath(fCompose(L(18, 2), H(18, 9, 0, 1))),
              @_Base( Scat(L(18, 2)) ),
              @_Base( VStack(
                  I(9), 
                  Interp(9)
                ),
                @_Base( I(9) ),
                Interp_base( Interp(9),
                  TCompose_tag( TCompose([ DFT(9, 1), TDiag(FData(D631)), DFT(9, 8) ]),
                    DFT_CT( DFT(9, 1),
                      DFT_Rader( DFT(3, 1),
                        DFT_Base( DFT(2, 1) ),
                        DFT_Base( DFT(2, 1) ) ),
                      DFT_Rader( DFT(3, 1),
                        DFT_Base( DFT(2, 1) ),
                        DFT_Base( DFT(2, 1) ) ) ),
                    TDiag_tag( TDiag(FData(D631)) ),
                    DFT_CT( DFT(9, 8),
                      DFT_Rader( DFT(3, 2),
                        DFT_Base( DFT(2, 1) ),
                        DFT_Base( DFT(2, 1) ) ),
                      DFT_Rader( DFT(3, 2),
                        DFT_Base( DFT(2, 1) ),
                        DFT_Base( DFT(2, 1) ) ) ) ) ) ),
              @_Base( Gath(fCompose(L(18, 2), H(18, 9, 0, 1))) ) ) ) ),
        IxA_vec_push( TTensorI(TL(4, 2, 1, 1), 5, APar, APar).withTags([ AVecRegCx(AVX_4x64f) ]),
          L_cx_real( TL(4, 2, 1, 1).withTags([ AVecRegCx(AVX_4x64f) ]),
            SIMD_ISA_Bases1( TL(4, 2, 1, 2).withTags([ AVecReg(AVX_4x64f) ]) ) ) ),
        Interp_vector( Interp(9).withTags([ AVecRegCx(AVX_4x64f) ]),
          DFT_tSPL_CT_oddvloop( DFT(9, 1).withTags([ AVecRegCx(AVX_4x64f) ]),
            @_Base( DPWrapper(DFT(3, 1), VWrap(AVX_4x64f)),
              DFT_Rader( DFT(3, 1),
                DFT_Base( DFT(2, 1) ),
                DFT_Base( DFT(2, 1) ) ) ),
            @_Base( DPWrapper(DFT(3, 1), VWrap(AVX_4x64f)),
              DFT_Rader( DFT(3, 1),
                DFT_Base( DFT(2, 1) ),
                DFT_Base( DFT(2, 1) ) ) ) ) ) ) ) ) )
*/

#include <math.h>
#include "omega64.h"
#include <malloc.h>
#include <immintrin.h>

void spiral_interpolate_packed_CPLX_init_run_9_9_9() {
}

void spiral_interpolate_packed_CPLX_run_9_9_9(double  *Y, double  *X) {
    for(int i13395 = 0; i13395 <= 8; i13395++) {
        static __attribute__((aligned(32))) double T2040[648];
        for(int i13397 = 0; i13397 <= 8; i13397++) {
            static __attribute__((aligned(32))) double T2044[18];
            static __attribute__((aligned(32))) double T2045[32];
            static __attribute__((aligned(32))) double T2046[32];
            __m128d U15182, U15184, U15185, U15186, U15187, U15188, U15189, U15190
    , U15191, U15192, U15193, U15194;
            __m256d U15183, s16390, s16391, s16392, s16393, s16394, s16395, s16396
    , s16397, s16398, s16399, s16400, s16401, s16402, s16403, s16404
    , s16405, s16406, s16407, s16408, s16409, s16410, s16411, s16412
    , s16413, s16414, s16415, s16416, s16417, s16418, s16419, s16420
    , s16421, s16422, s16423, s16424, s16425, s16426, s16427, s16428
    , s16429, s16430, s16431, s16432, s16433, s16434, s16435, s16436
    , s16437, s16438, s16439, s16440, s16441, s16442, s16443, s16444
    , s16445, s16446, s16447, t20041, t20042, t20043, t20044, t20045
    , t20046, t20047, t20048, t20049, t20050, t20051, t20052, t20053
    , t20054, t20055, t20056, t20057, t20058, t20059, t20060, t20061
    , t20062, t20063, t20064, t20065, t20066, t20067, t20068, t20069
    , t20070, t20071, t20072, t20073, t20074, t20075;
            double  *a20861;
            __m256d  *a20862;
            int a20860;
            a20860 = ((18)*(i13397));
            a20861 = (X + ((162)*(i13395)) + a20860);
            s16390 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd(a20861), 0), _mm_loadu_pd((2 + a20861)), 1);
            U15182 = _mm_loadu_pd((6 + a20861));
            U15183 = _mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd((4 + a20861)), 0);
            s16391 = _mm256_insertf128_pd(U15183, U15182, 1);
            U15184 = _mm_loadu_pd((8 + a20861));
            U15185 = _mm_loadu_pd((10 + a20861));
            s16392 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), U15184, 0), U15185, 1);
            s16393 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd((12 + a20861)), 0), _mm_loadu_pd((14 + a20861)), 1);
            s16394 = _mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd((16 + a20861)), 0);
            s16395 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), U15182, 0), U15184, 1);
            t20041 = _mm256_add_pd(s16395, s16393);
            t20042 = _mm256_sub_pd(s16390, _mm256_mul_pd(_mm256_set1_pd(0.5), t20041));
            s16396 = _mm256_add_pd(s16390, t20041);
            *(((__m256d  *) T2046)) = s16396;
            s16397 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s16395, s16393), _mm256_sub_pd(s16395, s16393), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t20043 = _mm256_add_pd(t20042, s16397);
            t20044 = _mm256_sub_pd(t20042, s16397);
            s16398 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.76604444311897801, 0.76604444311897801, 1.0, 1.0), t20043), _mm256_mul_pd(_mm256_set_pd((-0.64278760968653936), 0.64278760968653936, 0.0, 0.0), _mm256_shuffle_pd(t20043, t20043, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            *((2 + ((__m256d  *) T2046))) = s16398;
            s16399 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.17364817766693036, 0.17364817766693036, 1.0, 1.0), t20044), _mm256_mul_pd(_mm256_set_pd((-0.98480775301220802), 0.98480775301220802, 0.0, 0.0), _mm256_shuffle_pd(t20044, t20044, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            *((4 + ((__m256d  *) T2046))) = s16399;
            s16400 = _mm256_insertf128_pd(_mm256_setzero_pd(), U15185, 0);
            t20045 = _mm256_add_pd(s16400, s16394);
            t20046 = _mm256_sub_pd(U15183, _mm256_mul_pd(_mm256_set1_pd(0.5), t20045));
            s16401 = _mm256_mul_pd(_mm256_set_pd(0.0, 0.0, 1.0, 1.0), _mm256_add_pd(U15183, t20045));
            *((1 + ((__m256d  *) T2046))) = s16401;
            s16402 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s16400, s16394), _mm256_sub_pd(s16400, s16394), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t20047 = _mm256_add_pd(t20046, s16402);
            t20048 = _mm256_sub_pd(t20046, s16402);
            s16403 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.0, 0.0, 0.17364817766693036, 0.17364817766693036), t20047), _mm256_mul_pd(_mm256_set_pd(0.0, 0.0, (-0.98480775301220802), 0.98480775301220802), _mm256_shuffle_pd(t20047, t20047, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            *((3 + ((__m256d  *) T2046))) = s16403;
            s16404 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.0, 0.0, (-0.93969262078590843), (-0.93969262078590843)), t20048), _mm256_mul_pd(_mm256_set_pd(0.0, 0.0, (-0.34202014332566871), 0.34202014332566871), _mm256_shuffle_pd(t20048, t20048, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            *((5 + ((__m256d  *) T2046))) = s16404;
            s16405 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd(((double  *) T2046)), 0), _mm_loadu_pd((8 + ((double  *) T2046))), 1);
            s16406 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd((2 + ((double  *) T2046))), 0), _mm_loadu_pd((10 + ((double  *) T2046))), 1);
            s16407 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd((4 + ((double  *) T2046))), 0), _mm_loadu_pd((12 + ((double  *) T2046))), 1);
            t20049 = _mm256_add_pd(s16406, s16407);
            t20050 = _mm256_add_pd(s16405, t20049);
            t20051 = _mm256_sub_pd(s16405, _mm256_mul_pd(_mm256_set1_pd(0.5), t20049));
            s16408 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.10441029119843427, 0.10441029119843427, 0.1111111111111111, 0.1111111111111111), t20050), _mm256_mul_pd(_mm256_set_pd(0.038002238147296523, (-0.038002238147296523), 0.0, 0.0), _mm256_shuffle_pd(t20050, t20050, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s16409 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s16406, s16407), _mm256_sub_pd(s16406, s16407), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t20052 = _mm256_add_pd(t20051, s16409);
            t20053 = _mm256_sub_pd(t20051, s16409);
            s16410 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.019294241962992262, 0.019294241962992262, 0.055555555555555552, 0.055555555555555552), t20052), _mm256_mul_pd(_mm256_set_pd(0.10942308366802311, (-0.10942308366802311), 0.096225044864937617, (-0.096225044864937617)), _mm256_shuffle_pd(t20052, t20052, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s16411 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.085116049235441998, 0.085116049235441998, 0.055555555555555552, 0.055555555555555552), t20053), _mm256_mul_pd(_mm256_set_pd((-0.071420845520726597), 0.071420845520726597, (-0.096225044864937617), 0.096225044864937617), _mm256_shuffle_pd(t20053, t20053, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s16412 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd((16 + ((double  *) T2046))), 0), _mm_loadu_pd((24 + ((double  *) T2046))), 1);
            s16413 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd((18 + ((double  *) T2046))), 0), _mm_loadu_pd((26 + ((double  *) T2046))), 1);
            s16414 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd((20 + ((double  *) T2046))), 0), _mm_loadu_pd((28 + ((double  *) T2046))), 1);
            t20054 = _mm256_add_pd(s16413, s16414);
            t20055 = _mm256_add_pd(s16412, t20054);
            t20056 = _mm256_sub_pd(s16412, _mm256_mul_pd(_mm256_set1_pd(0.5), t20054));
            s16415 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.0, 0.0, 0.085116049235441998, 0.085116049235441998), t20055), _mm256_mul_pd(_mm256_set_pd(0.0, 0.0, 0.071420845520726597, (-0.071420845520726597)), _mm256_shuffle_pd(t20055, t20055, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s16416 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s16413, s16414), _mm256_sub_pd(s16413, s16414), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t20057 = _mm256_add_pd(t20056, s16416);
            t20058 = _mm256_sub_pd(t20056, s16416);
            s16417 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.0, 0.0, 0.019294241962992262, 0.019294241962992262), t20057), _mm256_mul_pd(_mm256_set_pd(0.0, 0.0, (-0.10942308366802311), 0.10942308366802311), _mm256_shuffle_pd(t20057, t20057, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s16418 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.0, 0.0, 0.10441029119843427, 0.10441029119843427), t20058), _mm256_mul_pd(_mm256_set_pd(0.0, 0.0, (-0.038002238147296523), 0.038002238147296523), _mm256_shuffle_pd(t20058, t20058, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t20059 = _mm256_add_pd(s16410, s16411);
            s16419 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s16410, s16411), _mm256_sub_pd(s16410, s16411), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t20060 = _mm256_add_pd(s16408, t20059);
            t20061 = _mm256_sub_pd(s16408, _mm256_mul_pd(_mm256_set1_pd(0.5), t20059));
            _mm_storeu_pd(((double  *) T2045), _mm256_extractf128_pd(t20060, 0));
            _mm_storeu_pd((8 + ((double  *) T2045)), _mm256_extractf128_pd(t20060, 1));
            t20062 = _mm256_add_pd(t20061, s16419);
            t20063 = _mm256_sub_pd(t20061, s16419);
            _mm_storeu_pd((2 + ((double  *) T2045)), _mm256_extractf128_pd(t20062, 0));
            _mm_storeu_pd((10 + ((double  *) T2045)), _mm256_extractf128_pd(t20062, 1));
            _mm_storeu_pd((4 + ((double  *) T2045)), _mm256_extractf128_pd(t20063, 0));
            _mm_storeu_pd((12 + ((double  *) T2045)), _mm256_extractf128_pd(t20063, 1));
            t20064 = _mm256_add_pd(s16417, s16418);
            s16420 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s16417, s16418), _mm256_sub_pd(s16417, s16418), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t20065 = _mm256_add_pd(s16415, t20064);
            t20066 = _mm256_sub_pd(s16415, _mm256_mul_pd(_mm256_set1_pd(0.5), t20064));
            _mm_storeu_pd((16 + ((double  *) T2045)), _mm256_extractf128_pd(t20065, 0));
            _mm_storeu_pd((24 + ((double  *) T2045)), _mm256_extractf128_pd(t20065, 1));
            t20067 = _mm256_add_pd(t20066, s16420);
            t20068 = _mm256_sub_pd(t20066, s16420);
            _mm_storeu_pd((18 + ((double  *) T2045)), _mm256_extractf128_pd(t20067, 0));
            _mm_storeu_pd((26 + ((double  *) T2045)), _mm256_extractf128_pd(t20067, 1));
            _mm_storeu_pd((20 + ((double  *) T2045)), _mm256_extractf128_pd(t20068, 0));
            _mm_storeu_pd((28 + ((double  *) T2045)), _mm256_extractf128_pd(t20068, 1));
            s16421 = *(((__m256d  *) T2045));
            s16422 = *((2 + ((__m256d  *) T2045)));
            s16423 = *((4 + ((__m256d  *) T2045)));
            s16424 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.76604444311897801, 0.76604444311897801, 1.0, 1.0), s16422), _mm256_mul_pd(_mm256_set_pd(0.64278760968653936, (-0.64278760968653936), 0.0, 0.0), _mm256_shuffle_pd(s16422, s16422, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s16425 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.17364817766693036, 0.17364817766693036, 1.0, 1.0), s16423), _mm256_mul_pd(_mm256_set_pd(0.98480775301220802, (-0.98480775301220802), 0.0, 0.0), _mm256_shuffle_pd(s16423, s16423, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t20069 = _mm256_add_pd(s16424, s16425);
            s16426 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s16424, s16425), _mm256_sub_pd(s16424, s16425), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t20070 = _mm256_add_pd(s16421, t20069);
            t20071 = _mm256_sub_pd(s16421, _mm256_mul_pd(_mm256_set1_pd(0.5), t20069));
            U15186 = _mm256_extractf128_pd(t20070, 0);
            _mm_storel_pd(((double  *) T2044), U15186);
            _mm_storeh_pd((1 + ((double  *) T2044)), U15186);
            U15187 = _mm256_extractf128_pd(t20070, 1);
            _mm_storel_pd((2 + ((double  *) T2044)), U15187);
            _mm_storeh_pd((3 + ((double  *) T2044)), U15187);
            t20072 = _mm256_add_pd(t20071, s16426);
            t20073 = _mm256_sub_pd(t20071, s16426);
            U15188 = _mm256_extractf128_pd(t20072, 0);
            _mm_storel_pd((6 + ((double  *) T2044)), U15188);
            _mm_storeh_pd((7 + ((double  *) T2044)), U15188);
            U15189 = _mm256_extractf128_pd(t20072, 1);
            _mm_storel_pd((8 + ((double  *) T2044)), U15189);
            _mm_storeh_pd((9 + ((double  *) T2044)), U15189);
            U15190 = _mm256_extractf128_pd(t20073, 0);
            _mm_storel_pd((12 + ((double  *) T2044)), U15190);
            _mm_storeh_pd((13 + ((double  *) T2044)), U15190);
            U15191 = _mm256_extractf128_pd(t20073, 1);
            _mm_storel_pd((14 + ((double  *) T2044)), U15191);
            _mm_storeh_pd((15 + ((double  *) T2044)), U15191);
            s16427 = _mm256_mul_pd(_mm256_set_pd(0.0, 0.0, 1.0, 1.0), *((1 + ((__m256d  *) T2045))));
            s16428 = *((3 + ((__m256d  *) T2045)));
            s16429 = *((5 + ((__m256d  *) T2045)));
            s16430 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.0, 0.0, 0.17364817766693036, 0.17364817766693036), s16428), _mm256_mul_pd(_mm256_set_pd(0.0, 0.0, 0.98480775301220802, (-0.98480775301220802)), _mm256_shuffle_pd(s16428, s16428, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s16431 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.0, 0.0, (-0.93969262078590843), (-0.93969262078590843)), s16429), _mm256_mul_pd(_mm256_set_pd(0.0, 0.0, 0.34202014332566871, (-0.34202014332566871)), _mm256_shuffle_pd(s16429, s16429, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t20074 = _mm256_add_pd(s16430, s16431);
            s16432 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s16430, s16431), _mm256_sub_pd(s16430, s16431), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t20075 = _mm256_sub_pd(s16427, _mm256_mul_pd(_mm256_set1_pd(0.5), t20074));
            U15192 = _mm256_extractf128_pd(_mm256_add_pd(s16427, t20074), 0);
            _mm_storel_pd((4 + ((double  *) T2044)), U15192);
            _mm_storeh_pd((5 + ((double  *) T2044)), U15192);
            U15193 = _mm256_extractf128_pd(_mm256_add_pd(t20075, s16432), 0);
            _mm_storel_pd((10 + ((double  *) T2044)), U15193);
            _mm_storeh_pd((11 + ((double  *) T2044)), U15193);
            U15194 = _mm256_extractf128_pd(_mm256_sub_pd(t20075, s16432), 0);
            _mm_storel_pd((16 + ((double  *) T2044)), U15194);
            _mm_storeh_pd((17 + ((double  *) T2044)), U15194);
            s16433 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd(((double  *) T2044)), 0), _mm_loadu_pd((2 + ((double  *) T2044))), 1);
            s16434 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd((4 + ((double  *) T2044))), 0), _mm_loadu_pd((6 + ((double  *) T2044))), 1);
            s16435 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd((8 + ((double  *) T2044))), 0), _mm_loadu_pd((10 + ((double  *) T2044))), 1);
            s16436 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd((12 + ((double  *) T2044))), 0), _mm_loadu_pd((14 + ((double  *) T2044))), 1);
            s16437 = _mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd((16 + ((double  *) T2044))), 0);
            a20862 = ((__m256d  *) T2040);
            s16438 = _mm256_permute2f128_pd(s16390, s16433, (0) | ((2) << 4));
            *((a20862 + a20860)) = s16438;
            s16439 = _mm256_permute2f128_pd(s16390, s16433, (1) | ((3) << 4));
            *((1 + a20862 + a20860)) = s16439;
            s16440 = _mm256_permute2f128_pd(s16391, s16434, (0) | ((2) << 4));
            *((2 + a20862 + a20860)) = s16440;
            s16441 = _mm256_permute2f128_pd(s16391, s16434, (1) | ((3) << 4));
            *((3 + a20862 + a20860)) = s16441;
            s16442 = _mm256_permute2f128_pd(s16392, s16435, (0) | ((2) << 4));
            *((4 + a20862 + a20860)) = s16442;
            s16443 = _mm256_permute2f128_pd(s16392, s16435, (1) | ((3) << 4));
            *((5 + a20862 + a20860)) = s16443;
            s16444 = _mm256_permute2f128_pd(s16393, s16436, (0) | ((2) << 4));
            *((6 + a20862 + a20860)) = s16444;
            s16445 = _mm256_permute2f128_pd(s16393, s16436, (1) | ((3) << 4));
            *((7 + a20862 + a20860)) = s16445;
            s16446 = _mm256_permute2f128_pd(s16394, s16437, (0) | ((2) << 4));
            *((8 + a20862 + a20860)) = s16446;
            s16447 = _mm256_permute2f128_pd(s16394, s16437, (1) | ((3) << 4));
            *((9 + a20862 + a20860)) = s16447;
        }
        for(int i13398 = 0; i13398 <= 8; i13398++) {
            __m256d s16562, s16563, s16564, s16565, s16566, s16567, s16568, s16569
    , s16570, s16571, s16572, s16573, s16574, s16575, s16576, s16577
    , s16578, s16579, s16580, s16581, s16582, s16583, s16584, s16585
    , s16586, s16587, s16588, s16589, s16590, s16591, s16592, s16593
    , s16594, s16595, s16596, s16597, s16598, s16599, t20279, t20280
    , t20281, t20282, t20283, t20284, t20285, t20286, t20287, t20288
    , t20289, t20290, t20291, t20292, t20293, t20294, t20295, t20296
    , t20297, t20298, t20299, t20300, t20301, t20302, t20303, t20304
    , t20305, t20306, t20307, t20308, t20309, t20310, t20311, t20312
    , t20313, t20314, t20315, t20316, t20317, t20318, t20319, t20320
    , t20321, t20322, t20323, t20324, t20325, t20326, t20327, t20328
    , t20329, t20330, t20331, t20332, t20333, t20334, t20335, t20336
    , t20337;
            double  *a21126;
            __m256d  *a21125;
            a21125 = ((__m256d  *) T2040);
            s16562 = *((a21125 + i13398));
            s16563 = *((18 + a21125 + i13398));
            s16564 = *((36 + a21125 + i13398));
            s16565 = *((54 + a21125 + i13398));
            s16566 = *((72 + a21125 + i13398));
            s16567 = *((90 + a21125 + i13398));
            s16568 = *((108 + a21125 + i13398));
            s16569 = *((126 + a21125 + i13398));
            s16570 = *((144 + a21125 + i13398));
            a21126 = (Y + ((1296)*(i13395)) + ((4)*(i13398)));
            _mm_storeu_pd(a21126, _mm256_extractf128_pd(s16562, 0));
            _mm_storeu_pd((2 + a21126), _mm256_extractf128_pd(s16562, 1));
            _mm_storeu_pd((72 + a21126), _mm256_extractf128_pd(s16563, 0));
            _mm_storeu_pd((74 + a21126), _mm256_extractf128_pd(s16563, 1));
            _mm_storeu_pd((144 + a21126), _mm256_extractf128_pd(s16564, 0));
            _mm_storeu_pd((146 + a21126), _mm256_extractf128_pd(s16564, 1));
            _mm_storeu_pd((216 + a21126), _mm256_extractf128_pd(s16565, 0));
            _mm_storeu_pd((218 + a21126), _mm256_extractf128_pd(s16565, 1));
            _mm_storeu_pd((288 + a21126), _mm256_extractf128_pd(s16566, 0));
            _mm_storeu_pd((290 + a21126), _mm256_extractf128_pd(s16566, 1));
            _mm_storeu_pd((360 + a21126), _mm256_extractf128_pd(s16567, 0));
            _mm_storeu_pd((362 + a21126), _mm256_extractf128_pd(s16567, 1));
            _mm_storeu_pd((432 + a21126), _mm256_extractf128_pd(s16568, 0));
            _mm_storeu_pd((434 + a21126), _mm256_extractf128_pd(s16568, 1));
            _mm_storeu_pd((504 + a21126), _mm256_extractf128_pd(s16569, 0));
            _mm_storeu_pd((506 + a21126), _mm256_extractf128_pd(s16569, 1));
            _mm_storeu_pd((576 + a21126), _mm256_extractf128_pd(s16570, 0));
            _mm_storeu_pd((578 + a21126), _mm256_extractf128_pd(s16570, 1));
            t20279 = _mm256_add_pd(s16565, s16568);
            s16571 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s16565, s16568), _mm256_sub_pd(s16565, s16568), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t20280 = _mm256_add_pd(s16562, t20279);
            t20281 = _mm256_sub_pd(s16562, _mm256_mul_pd(_mm256_set1_pd(0.5), t20279));
            t20282 = _mm256_add_pd(t20281, s16571);
            t20283 = _mm256_sub_pd(t20281, s16571);
            t20284 = _mm256_add_pd(s16566, s16569);
            s16572 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s16566, s16569), _mm256_sub_pd(s16566, s16569), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t20285 = _mm256_add_pd(s16563, t20284);
            t20286 = _mm256_sub_pd(s16563, _mm256_mul_pd(_mm256_set1_pd(0.5), t20284));
            t20287 = _mm256_add_pd(t20286, s16572);
            t20288 = _mm256_sub_pd(t20286, s16572);
            s16573 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.76604444311897801), t20287), _mm256_mul_pd(_mm256_set_pd((-0.64278760968653936), 0.64278760968653936, (-0.64278760968653936), 0.64278760968653936), _mm256_shuffle_pd(t20287, t20287, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s16574 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.17364817766693036), t20288), _mm256_mul_pd(_mm256_set_pd((-0.98480775301220802), 0.98480775301220802, (-0.98480775301220802), 0.98480775301220802), _mm256_shuffle_pd(t20288, t20288, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t20289 = _mm256_add_pd(s16567, s16570);
            s16575 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s16567, s16570), _mm256_sub_pd(s16567, s16570), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t20290 = _mm256_add_pd(s16564, t20289);
            t20291 = _mm256_sub_pd(s16564, _mm256_mul_pd(_mm256_set1_pd(0.5), t20289));
            t20292 = _mm256_add_pd(t20291, s16575);
            t20293 = _mm256_sub_pd(t20291, s16575);
            s16576 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.17364817766693036), t20292), _mm256_mul_pd(_mm256_set_pd((-0.98480775301220802), 0.98480775301220802, (-0.98480775301220802), 0.98480775301220802), _mm256_shuffle_pd(t20292, t20292, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s16577 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd((-0.93969262078590843)), t20293), _mm256_mul_pd(_mm256_set_pd((-0.34202014332566871), 0.34202014332566871, (-0.34202014332566871), 0.34202014332566871), _mm256_shuffle_pd(t20293, t20293, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t20294 = _mm256_add_pd(t20285, t20290);
            s16578 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(t20285, t20290), _mm256_sub_pd(t20285, t20290), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t20295 = _mm256_sub_pd(t20280, _mm256_mul_pd(_mm256_set1_pd(0.5), t20294));
            s16579 = _mm256_mul_pd(_mm256_set1_pd(0.1111111111111111), _mm256_add_pd(t20280, t20294));
            t20296 = _mm256_add_pd(t20295, s16578);
            t20297 = _mm256_sub_pd(t20295, s16578);
            s16580 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.055555555555555552), t20296), _mm256_mul_pd(_mm256_set_pd(0.096225044864937617, (-0.096225044864937617), 0.096225044864937617, (-0.096225044864937617)), _mm256_shuffle_pd(t20296, t20296, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s16581 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.055555555555555552), t20297), _mm256_mul_pd(_mm256_set_pd((-0.096225044864937617), 0.096225044864937617, (-0.096225044864937617), 0.096225044864937617), _mm256_shuffle_pd(t20297, t20297, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t20298 = _mm256_add_pd(s16573, s16576);
            s16582 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s16573, s16576), _mm256_sub_pd(s16573, s16576), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t20299 = _mm256_add_pd(t20282, t20298);
            t20300 = _mm256_sub_pd(t20282, _mm256_mul_pd(_mm256_set1_pd(0.5), t20298));
            s16583 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.10441029119843427), t20299), _mm256_mul_pd(_mm256_set_pd(0.038002238147296523, (-0.038002238147296523), 0.038002238147296523, (-0.038002238147296523)), _mm256_shuffle_pd(t20299, t20299, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t20301 = _mm256_add_pd(t20300, s16582);
            t20302 = _mm256_sub_pd(t20300, s16582);
            s16584 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.019294241962992262), t20301), _mm256_mul_pd(_mm256_set_pd(0.10942308366802311, (-0.10942308366802311), 0.10942308366802311, (-0.10942308366802311)), _mm256_shuffle_pd(t20301, t20301, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s16585 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.085116049235441998), t20302), _mm256_mul_pd(_mm256_set_pd((-0.071420845520726597), 0.071420845520726597, (-0.071420845520726597), 0.071420845520726597), _mm256_shuffle_pd(t20302, t20302, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t20303 = _mm256_add_pd(s16574, s16577);
            s16586 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s16574, s16577), _mm256_sub_pd(s16574, s16577), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t20304 = _mm256_add_pd(t20283, t20303);
            t20305 = _mm256_sub_pd(t20283, _mm256_mul_pd(_mm256_set1_pd(0.5), t20303));
            s16587 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.085116049235441998), t20304), _mm256_mul_pd(_mm256_set_pd(0.071420845520726597, (-0.071420845520726597), 0.071420845520726597, (-0.071420845520726597)), _mm256_shuffle_pd(t20304, t20304, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t20306 = _mm256_add_pd(t20305, s16586);
            t20307 = _mm256_sub_pd(t20305, s16586);
            s16588 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.019294241962992262), t20306), _mm256_mul_pd(_mm256_set_pd((-0.10942308366802311), 0.10942308366802311, (-0.10942308366802311), 0.10942308366802311), _mm256_shuffle_pd(t20306, t20306, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s16589 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.10441029119843427), t20307), _mm256_mul_pd(_mm256_set_pd((-0.038002238147296523), 0.038002238147296523, (-0.038002238147296523), 0.038002238147296523), _mm256_shuffle_pd(t20307, t20307, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t20308 = _mm256_add_pd(s16580, s16581);
            s16590 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s16580, s16581), _mm256_sub_pd(s16580, s16581), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t20309 = _mm256_add_pd(s16579, t20308);
            t20310 = _mm256_sub_pd(s16579, _mm256_mul_pd(_mm256_set1_pd(0.5), t20308));
            t20311 = _mm256_add_pd(t20310, s16590);
            t20312 = _mm256_sub_pd(t20310, s16590);
            t20313 = _mm256_add_pd(s16584, s16585);
            s16591 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s16584, s16585), _mm256_sub_pd(s16584, s16585), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t20314 = _mm256_add_pd(s16583, t20313);
            t20315 = _mm256_sub_pd(s16583, _mm256_mul_pd(_mm256_set1_pd(0.5), t20313));
            t20316 = _mm256_add_pd(t20315, s16591);
            t20317 = _mm256_sub_pd(t20315, s16591);
            s16592 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.76604444311897801), t20316), _mm256_mul_pd(_mm256_set_pd(0.64278760968653936, (-0.64278760968653936), 0.64278760968653936, (-0.64278760968653936)), _mm256_shuffle_pd(t20316, t20316, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s16593 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.17364817766693036), t20317), _mm256_mul_pd(_mm256_set_pd(0.98480775301220802, (-0.98480775301220802), 0.98480775301220802, (-0.98480775301220802)), _mm256_shuffle_pd(t20317, t20317, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t20318 = _mm256_add_pd(s16588, s16589);
            s16594 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s16588, s16589), _mm256_sub_pd(s16588, s16589), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t20319 = _mm256_add_pd(s16587, t20318);
            t20320 = _mm256_sub_pd(s16587, _mm256_mul_pd(_mm256_set1_pd(0.5), t20318));
            t20321 = _mm256_add_pd(t20320, s16594);
            t20322 = _mm256_sub_pd(t20320, s16594);
            s16595 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.17364817766693036), t20321), _mm256_mul_pd(_mm256_set_pd(0.98480775301220802, (-0.98480775301220802), 0.98480775301220802, (-0.98480775301220802)), _mm256_shuffle_pd(t20321, t20321, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s16596 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd((-0.93969262078590843)), t20322), _mm256_mul_pd(_mm256_set_pd(0.34202014332566871, (-0.34202014332566871), 0.34202014332566871, (-0.34202014332566871)), _mm256_shuffle_pd(t20322, t20322, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t20323 = _mm256_add_pd(t20314, t20319);
            s16597 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(t20314, t20319), _mm256_sub_pd(t20314, t20319), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t20324 = _mm256_add_pd(t20309, t20323);
            t20325 = _mm256_sub_pd(t20309, _mm256_mul_pd(_mm256_set1_pd(0.5), t20323));
            _mm_storeu_pd((36 + a21126), _mm256_extractf128_pd(t20324, 0));
            _mm_storeu_pd((38 + a21126), _mm256_extractf128_pd(t20324, 1));
            t20326 = _mm256_add_pd(t20325, s16597);
            t20327 = _mm256_sub_pd(t20325, s16597);
            _mm_storeu_pd((252 + a21126), _mm256_extractf128_pd(t20326, 0));
            _mm_storeu_pd((254 + a21126), _mm256_extractf128_pd(t20326, 1));
            _mm_storeu_pd((468 + a21126), _mm256_extractf128_pd(t20327, 0));
            _mm_storeu_pd((470 + a21126), _mm256_extractf128_pd(t20327, 1));
            t20328 = _mm256_add_pd(s16592, s16595);
            s16598 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s16592, s16595), _mm256_sub_pd(s16592, s16595), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t20329 = _mm256_add_pd(t20311, t20328);
            t20330 = _mm256_sub_pd(t20311, _mm256_mul_pd(_mm256_set1_pd(0.5), t20328));
            _mm_storeu_pd((108 + a21126), _mm256_extractf128_pd(t20329, 0));
            _mm_storeu_pd((110 + a21126), _mm256_extractf128_pd(t20329, 1));
            t20331 = _mm256_add_pd(t20330, s16598);
            t20332 = _mm256_sub_pd(t20330, s16598);
            _mm_storeu_pd((324 + a21126), _mm256_extractf128_pd(t20331, 0));
            _mm_storeu_pd((326 + a21126), _mm256_extractf128_pd(t20331, 1));
            _mm_storeu_pd((540 + a21126), _mm256_extractf128_pd(t20332, 0));
            _mm_storeu_pd((542 + a21126), _mm256_extractf128_pd(t20332, 1));
            t20333 = _mm256_add_pd(s16593, s16596);
            s16599 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s16593, s16596), _mm256_sub_pd(s16593, s16596), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t20334 = _mm256_add_pd(t20312, t20333);
            t20335 = _mm256_sub_pd(t20312, _mm256_mul_pd(_mm256_set1_pd(0.5), t20333));
            _mm_storeu_pd((180 + a21126), _mm256_extractf128_pd(t20334, 0));
            _mm_storeu_pd((182 + a21126), _mm256_extractf128_pd(t20334, 1));
            t20336 = _mm256_add_pd(t20335, s16599);
            t20337 = _mm256_sub_pd(t20335, s16599);
            _mm_storeu_pd((396 + a21126), _mm256_extractf128_pd(t20336, 0));
            _mm_storeu_pd((398 + a21126), _mm256_extractf128_pd(t20336, 1));
            _mm_storeu_pd((612 + a21126), _mm256_extractf128_pd(t20337, 0));
            _mm_storeu_pd((614 + a21126), _mm256_extractf128_pd(t20337, 1));
        }
    }
    for(int i13400 = 0; i13400 <= 161; i13400++) {
        __m256d s16723, s16724, s16725, s16726, s16727, s16728, s16729, s16730
    , s16731, s16732, s16733, s16734, s16735, s16736, s16737, s16738
    , s16739, s16740, s16741, s16742, s16743, s16744, s16745, s16746
    , s16747, s16748, s16749, s16750, s16751, s16752, s16753, s16754
    , s16755, s16756, s16757, s16758, s16759, s16760, s16761, s16762
    , s16763, s16764, s16765, s16766, s16767, s16768, s16769, t20532
    , t20533, t20534, t20535, t20536, t20537, t20538, t20539, t20540
    , t20541, t20542, t20543, t20544, t20545, t20546, t20547, t20548
    , t20549, t20550, t20551, t20552, t20553, t20554, t20555, t20556
    , t20557, t20558, t20559, t20560, t20561, t20562, t20563, t20564
    , t20565, t20566, t20567, t20568, t20569, t20570, t20571, t20572
    , t20573, t20574, t20575, t20576, t20577, t20578, t20579, t20580
    , t20581;
        __m256d  *a21269;
        a21269 = ((__m256d  *) Y);
        s16723 = *((a21269 + i13400));
        s16724 = *((972 + a21269 + i13400));
        s16725 = *((1944 + a21269 + i13400));
        t20532 = _mm256_add_pd(s16724, s16725);
        s16726 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s16724, s16725), _mm256_sub_pd(s16724, s16725), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t20533 = _mm256_add_pd(s16723, t20532);
        t20534 = _mm256_sub_pd(s16723, _mm256_mul_pd(_mm256_set1_pd(0.5), t20532));
        t20535 = _mm256_add_pd(t20534, s16726);
        t20536 = _mm256_sub_pd(t20534, s16726);
        s16727 = *((324 + a21269 + i13400));
        s16728 = *((1296 + a21269 + i13400));
        s16729 = *((2268 + a21269 + i13400));
        t20537 = _mm256_add_pd(s16728, s16729);
        s16730 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s16728, s16729), _mm256_sub_pd(s16728, s16729), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t20538 = _mm256_add_pd(s16727, t20537);
        t20539 = _mm256_sub_pd(s16727, _mm256_mul_pd(_mm256_set1_pd(0.5), t20537));
        t20540 = _mm256_add_pd(t20539, s16730);
        t20541 = _mm256_sub_pd(t20539, s16730);
        s16731 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.76604444311897801), t20540), _mm256_mul_pd(_mm256_set_pd((-0.64278760968653936), 0.64278760968653936, (-0.64278760968653936), 0.64278760968653936), _mm256_shuffle_pd(t20540, t20540, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        s16732 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.17364817766693036), t20541), _mm256_mul_pd(_mm256_set_pd((-0.98480775301220802), 0.98480775301220802, (-0.98480775301220802), 0.98480775301220802), _mm256_shuffle_pd(t20541, t20541, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        s16733 = *((648 + a21269 + i13400));
        s16734 = *((1620 + a21269 + i13400));
        s16735 = *((2592 + a21269 + i13400));
        t20542 = _mm256_add_pd(s16734, s16735);
        s16736 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s16734, s16735), _mm256_sub_pd(s16734, s16735), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t20543 = _mm256_add_pd(s16733, t20542);
        t20544 = _mm256_sub_pd(s16733, _mm256_mul_pd(_mm256_set1_pd(0.5), t20542));
        t20545 = _mm256_add_pd(t20544, s16736);
        t20546 = _mm256_sub_pd(t20544, s16736);
        s16737 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.17364817766693036), t20545), _mm256_mul_pd(_mm256_set_pd((-0.98480775301220802), 0.98480775301220802, (-0.98480775301220802), 0.98480775301220802), _mm256_shuffle_pd(t20545, t20545, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        s16738 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd((-0.93969262078590843)), t20546), _mm256_mul_pd(_mm256_set_pd((-0.34202014332566871), 0.34202014332566871, (-0.34202014332566871), 0.34202014332566871), _mm256_shuffle_pd(t20546, t20546, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        t20547 = _mm256_add_pd(t20538, t20543);
        s16739 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(t20538, t20543), _mm256_sub_pd(t20538, t20543), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t20548 = _mm256_sub_pd(t20533, _mm256_mul_pd(_mm256_set1_pd(0.5), t20547));
        s16740 = _mm256_mul_pd(_mm256_set1_pd(0.1111111111111111), _mm256_add_pd(t20533, t20547));
        t20549 = _mm256_add_pd(t20548, s16739);
        t20550 = _mm256_sub_pd(t20548, s16739);
        s16741 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.055555555555555552), t20549), _mm256_mul_pd(_mm256_set_pd(0.096225044864937617, (-0.096225044864937617), 0.096225044864937617, (-0.096225044864937617)), _mm256_shuffle_pd(t20549, t20549, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        s16742 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.055555555555555552), t20550), _mm256_mul_pd(_mm256_set_pd((-0.096225044864937617), 0.096225044864937617, (-0.096225044864937617), 0.096225044864937617), _mm256_shuffle_pd(t20550, t20550, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        t20551 = _mm256_add_pd(s16731, s16737);
        s16743 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s16731, s16737), _mm256_sub_pd(s16731, s16737), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t20552 = _mm256_add_pd(t20535, t20551);
        t20553 = _mm256_sub_pd(t20535, _mm256_mul_pd(_mm256_set1_pd(0.5), t20551));
        s16744 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.10441029119843427), t20552), _mm256_mul_pd(_mm256_set_pd(0.038002238147296523, (-0.038002238147296523), 0.038002238147296523, (-0.038002238147296523)), _mm256_shuffle_pd(t20552, t20552, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        t20554 = _mm256_add_pd(t20553, s16743);
        t20555 = _mm256_sub_pd(t20553, s16743);
        s16745 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.019294241962992262), t20554), _mm256_mul_pd(_mm256_set_pd(0.10942308366802311, (-0.10942308366802311), 0.10942308366802311, (-0.10942308366802311)), _mm256_shuffle_pd(t20554, t20554, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        s16746 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.085116049235441998), t20555), _mm256_mul_pd(_mm256_set_pd((-0.071420845520726597), 0.071420845520726597, (-0.071420845520726597), 0.071420845520726597), _mm256_shuffle_pd(t20555, t20555, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        t20556 = _mm256_add_pd(s16732, s16738);
        s16747 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s16732, s16738), _mm256_sub_pd(s16732, s16738), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t20557 = _mm256_add_pd(t20536, t20556);
        t20558 = _mm256_sub_pd(t20536, _mm256_mul_pd(_mm256_set1_pd(0.5), t20556));
        s16748 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.085116049235441998), t20557), _mm256_mul_pd(_mm256_set_pd(0.071420845520726597, (-0.071420845520726597), 0.071420845520726597, (-0.071420845520726597)), _mm256_shuffle_pd(t20557, t20557, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        t20559 = _mm256_add_pd(t20558, s16747);
        t20560 = _mm256_sub_pd(t20558, s16747);
        s16749 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.019294241962992262), t20559), _mm256_mul_pd(_mm256_set_pd((-0.10942308366802311), 0.10942308366802311, (-0.10942308366802311), 0.10942308366802311), _mm256_shuffle_pd(t20559, t20559, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        s16750 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.10441029119843427), t20560), _mm256_mul_pd(_mm256_set_pd((-0.038002238147296523), 0.038002238147296523, (-0.038002238147296523), 0.038002238147296523), _mm256_shuffle_pd(t20560, t20560, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        t20561 = _mm256_add_pd(s16741, s16742);
        s16751 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s16741, s16742), _mm256_sub_pd(s16741, s16742), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t20562 = _mm256_add_pd(s16740, t20561);
        t20563 = _mm256_sub_pd(s16740, _mm256_mul_pd(_mm256_set1_pd(0.5), t20561));
        t20564 = _mm256_add_pd(t20563, s16751);
        t20565 = _mm256_sub_pd(t20563, s16751);
        t20566 = _mm256_add_pd(s16745, s16746);
        s16752 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s16745, s16746), _mm256_sub_pd(s16745, s16746), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t20567 = _mm256_add_pd(s16744, t20566);
        t20568 = _mm256_sub_pd(s16744, _mm256_mul_pd(_mm256_set1_pd(0.5), t20566));
        t20569 = _mm256_add_pd(t20568, s16752);
        t20570 = _mm256_sub_pd(t20568, s16752);
        s16753 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.76604444311897801), t20569), _mm256_mul_pd(_mm256_set_pd(0.64278760968653936, (-0.64278760968653936), 0.64278760968653936, (-0.64278760968653936)), _mm256_shuffle_pd(t20569, t20569, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        s16754 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.17364817766693036), t20570), _mm256_mul_pd(_mm256_set_pd(0.98480775301220802, (-0.98480775301220802), 0.98480775301220802, (-0.98480775301220802)), _mm256_shuffle_pd(t20570, t20570, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        t20571 = _mm256_add_pd(s16749, s16750);
        s16755 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s16749, s16750), _mm256_sub_pd(s16749, s16750), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t20572 = _mm256_add_pd(s16748, t20571);
        t20573 = _mm256_sub_pd(s16748, _mm256_mul_pd(_mm256_set1_pd(0.5), t20571));
        t20574 = _mm256_add_pd(t20573, s16755);
        t20575 = _mm256_sub_pd(t20573, s16755);
        s16756 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.17364817766693036), t20574), _mm256_mul_pd(_mm256_set_pd(0.98480775301220802, (-0.98480775301220802), 0.98480775301220802, (-0.98480775301220802)), _mm256_shuffle_pd(t20574, t20574, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        s16757 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd((-0.93969262078590843)), t20575), _mm256_mul_pd(_mm256_set_pd(0.34202014332566871, (-0.34202014332566871), 0.34202014332566871, (-0.34202014332566871)), _mm256_shuffle_pd(t20575, t20575, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        t20576 = _mm256_add_pd(t20567, t20572);
        s16758 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(t20567, t20572), _mm256_sub_pd(t20567, t20572), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t20577 = _mm256_sub_pd(t20562, _mm256_mul_pd(_mm256_set1_pd(0.5), t20576));
        s16759 = _mm256_add_pd(t20562, t20576);
        *((162 + a21269 + i13400)) = s16759;
        s16760 = _mm256_add_pd(t20577, s16758);
        *((1134 + a21269 + i13400)) = s16760;
        s16761 = _mm256_sub_pd(t20577, s16758);
        *((2106 + a21269 + i13400)) = s16761;
        t20578 = _mm256_add_pd(s16753, s16756);
        s16762 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s16753, s16756), _mm256_sub_pd(s16753, s16756), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t20579 = _mm256_sub_pd(t20564, _mm256_mul_pd(_mm256_set1_pd(0.5), t20578));
        s16763 = _mm256_add_pd(t20564, t20578);
        *((486 + a21269 + i13400)) = s16763;
        s16764 = _mm256_add_pd(t20579, s16762);
        *((1458 + a21269 + i13400)) = s16764;
        s16765 = _mm256_sub_pd(t20579, s16762);
        *((2430 + a21269 + i13400)) = s16765;
        t20580 = _mm256_add_pd(s16754, s16757);
        s16766 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s16754, s16757), _mm256_sub_pd(s16754, s16757), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t20581 = _mm256_sub_pd(t20565, _mm256_mul_pd(_mm256_set1_pd(0.5), t20580));
        s16767 = _mm256_add_pd(t20565, t20580);
        *((810 + a21269 + i13400)) = s16767;
        s16768 = _mm256_add_pd(t20581, s16766);
        *((1782 + a21269 + i13400)) = s16768;
        s16769 = _mm256_sub_pd(t20581, s16766);
        *((2754 + a21269 + i13400)) = s16769;
    }
}

void spiral_interpolate_packed_CPLX_del_run_9_9_9(void) {
}
