/***************************************************************
This code was generated by  Spiral 6.0 beta, www.spiral.net --
Copyright (c) 2005, Carnegie Mellon University
All rights reserved.
The code is distributed under a BSD style license
(see http://www.opensource.org/licenses/bsd-license.php)

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

* Redistributions of source code must retain the above copyright
  notice, reference to Spiral, this list of conditions and the
  following disclaimer.
* Redistributions in binary form must reproduce the above
  copyright notice, this list of conditions and the following
  disclaimer in the documentation and/or other materials provided
  with the distribution.
* Neither the name of Carnegie Mellon University nor the name of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
*AS IS* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
******************************************************************/

/*	CPU: Intel Core i7 at 3500 MHz, 4 cores, SSE4_2
	OS: Linux64
	SVN: 99/113 (modified)
	profile: linux-x86-multipleio, -O2 -Wall -fomit-frame-pointer -mavx -std=c99
	timestamp: Oct 7, 2014; 23:29:17
	transform: TSplit(PSInterpolationStage(1, 9, 9, 9)).withTags([ AVecReg(AVX_4x64f) ])
	source file: "opts_cplx_TSplit_PSInterpolationStage_1_9_9_9.c(.c)"
	performance: 50612.0 cycles, 0 Mflop/s

algorithm: TSplit_cplxvect( TSplit(PSInterpolationStage(1, 9, 9, 9)).withTags([ AVecReg(AVX_4x64f) ]),
  @_Base( DPWrapper(PSInterpolationStage(1, 9, 9, 9).withTags([ AVecRegCx(AVX_4x64f) ]), VWrapTRCcplx(AVX_4x64f)),
    PSInterpolationStage_3dv_special( PSInterpolationStage(1, 9, 9, 9).withTags([ AVecRegCx(AVX_4x64f) ]),
      AxI_vec( TTensorI(Scat(L(18, 2)) * 
          VStack(
            I(9), 
            Interp(9)
          ) * 
          Gath(fCompose(L(18, 2), H(18, 9, 0, 1))), 324, AVec, AVec).withTags([ AVecRegCx(AVX_4x64f) ]),
        AxI_base( TTensorI(DPWrapper(Scat(L(18, 2)) * 
              VStack(
                I(9), 
                Interp(9)
              ) * 
              Gath(fCompose(L(18, 2), H(18, 9, 0, 1))), VWrap(AVX_4x64f)), 162, AVec, AVec),
          @_Base( DPWrapper(Scat(L(18, 2)) * 
              VStack(
                I(9), 
                Interp(9)
              ) * 
              Gath(fCompose(L(18, 2), H(18, 9, 0, 1))), VWrap(AVX_4x64f)),
            @_Base( Scat(L(18, 2)) * 
              VStack(
                I(9), 
                Interp(9)
              ) * 
              Gath(fCompose(L(18, 2), H(18, 9, 0, 1))),
              @_Base( Scat(L(18, 2)) ),
              @_Base( VStack(
                  I(9), 
                  Interp(9)
                ),
                @_Base( I(9) ),
                Interp_base( Interp(9),
                  TCompose_tag( TCompose([ DFT(9, 1), TDiag(FData(D48789)), DFT(9, 8) ]),
                    DFT_CT( DFT(9, 1),
                      DFT_Rader( DFT(3, 1),
                        DFT_Base( DFT(2, 1) ),
                        DFT_Base( DFT(2, 1) ) ),
                      DFT_Rader( DFT(3, 1),
                        DFT_Base( DFT(2, 1) ),
                        DFT_Base( DFT(2, 1) ) ) ),
                    TDiag_tag( TDiag(FData(D48789)) ),
                    DFT_CT( DFT(9, 8),
                      DFT_Rader( DFT(3, 2),
                        DFT_Base( DFT(2, 1) ),
                        DFT_Base( DFT(2, 1) ) ),
                      DFT_Rader( DFT(3, 2),
                        DFT_Base( DFT(2, 1) ),
                        DFT_Base( DFT(2, 1) ) ) ) ) ) ),
              @_Base( Gath(fCompose(L(18, 2), H(18, 9, 0, 1))) ) ) ) ) ),
      PSInterpolationStage_2dv( PSInterpolationStage(2, 1, 9, 9).withTags([ AVecRegCx(AVX_4x64f) ]),
        AxI_vec( TTensorI(Scat(L(18, 2)) * 
            VStack(
              I(9), 
              Interp(9)
            ) * 
            Gath(fCompose(L(18, 2), H(18, 9, 0, 1))), 2, AVec, AVec).withTags([ AVecRegCx(AVX_4x64f) ]),
          @_Base( DPWrapper(Scat(L(18, 2)) * 
              VStack(
                I(9), 
                Interp(9)
              ) * 
              Gath(fCompose(L(18, 2), H(18, 9, 0, 1))), VWrap(AVX_4x64f)),
            @_Base( Scat(L(18, 2)) * 
              VStack(
                I(9), 
                Interp(9)
              ) * 
              Gath(fCompose(L(18, 2), H(18, 9, 0, 1))),
              @_Base( Scat(L(18, 2)) ),
              @_Base( VStack(
                  I(9), 
                  Interp(9)
                ),
                @_Base( I(9) ),
                Interp_base( Interp(9),
                  TCompose_tag( TCompose([ DFT(9, 1), TDiag(FData(D48791)), DFT(9, 8) ]),
                    DFT_CT( DFT(9, 1),
                      DFT_Rader( DFT(3, 1),
                        DFT_Base( DFT(2, 1) ),
                        DFT_Base( DFT(2, 1) ) ),
                      DFT_Rader( DFT(3, 1),
                        DFT_Base( DFT(2, 1) ),
                        DFT_Base( DFT(2, 1) ) ) ),
                    TDiag_tag( TDiag(FData(D48791)) ),
                    DFT_CT( DFT(9, 8),
                      DFT_Rader( DFT(3, 2),
                        DFT_Base( DFT(2, 1) ),
                        DFT_Base( DFT(2, 1) ) ),
                      DFT_Rader( DFT(3, 2),
                        DFT_Base( DFT(2, 1) ),
                        DFT_Base( DFT(2, 1) ) ) ) ) ) ),
              @_Base( Gath(fCompose(L(18, 2), H(18, 9, 0, 1))) ) ) ) ),
        IxA_vec_push( TTensorI(TL(4, 2, 1, 1), 5, APar, APar).withTags([ AVecRegCx(AVX_4x64f) ]),
          L_cx_real( TL(4, 2, 1, 1).withTags([ AVecRegCx(AVX_4x64f) ]),
            SIMD_ISA_Bases1( TL(4, 2, 1, 2).withTags([ AVecReg(AVX_4x64f) ]) ) ) ),
        Interp_vector( Interp(9).withTags([ AVecRegCx(AVX_4x64f) ]),
          DFT_tSPL_CT_oddvloop( DFT(9, 1).withTags([ AVecRegCx(AVX_4x64f) ]),
            @_Base( DPWrapper(DFT(3, 1), VWrap(AVX_4x64f)),
              DFT_Rader( DFT(3, 1),
                DFT_Base( DFT(2, 1) ),
                DFT_Base( DFT(2, 1) ) ) ),
            @_Base( DPWrapper(DFT(3, 1), VWrap(AVX_4x64f)),
              DFT_Rader( DFT(3, 1),
                DFT_Base( DFT(2, 1) ),
                DFT_Base( DFT(2, 1) ) ) ) ) ) ) ) ) )
*/

#include <math.h>
#include "omega64.h"
#include <malloc.h>
#include <immintrin.h>

void spiral_interpolate_split_CPLX_init_run_9_9_9() {
}

void spiral_interpolate_split_CPLX_run_9_9_9(double  *Y1, double  *Y2, double  *X1, double  *X2) {
    for(int i1511776 = 0; i1511776 <= 8; i1511776++) {
        static __attribute__((aligned(32))) double T197198[648];
        for(int i1511778 = 0; i1511778 <= 8; i1511778++) {
            static __attribute__((aligned(32))) double T197202[18];
            static __attribute__((aligned(32))) double T197203[32];
            static __attribute__((aligned(32))) double T197204[32];
            __m128d U2304568, U2304569, U2304570, U2304571, U2304572, U2304573, U2304574, U2304575
    , U2304576, U2304577, U2304578, U2304579;
            __m256d s3336945, s3336946, s3336947, s3336948, s3336949, s3336950, s3336951, s3336952
    , s3336953, s3336954, s3336955, s3336956, s3336957, s3336958, s3336959, s3336960
    , s3336961, s3336962, s3336963, s3336964, s3336965, s3336966, s3336967, s3336968
    , s3336969, s3336970, s3336971, s3336972, s3336973, s3336974, s3336975, s3336976
    , s3336977, s3336978, s3336979, s3336980, s3336981, s3336982, s3336983, s3336984
    , s3336985, s3336986, s3336987, s3336988, s3336989, s3336990, s3336991, s3336992
    , s3336993, s3336994, s3336995, s3336996, s3336997, s3336998, s3336999, s3337000
    , s3337001, s3337002, s3337003, s3337004, t5624339, t5624340, t5624341, t5624342
    , t5624343, t5624344, t5624345, t5624346, t5624347, t5624348, t5624349, t5624350
    , t5624351, t5624352, t5624353, t5624354, t5624355, t5624356, t5624357, t5624358
    , t5624359, t5624360, t5624361, t5624362, t5624363, t5624364, t5624365, t5624366
    , t5624367, t5624368, t5624369, t5624370, t5624371, t5624372, t5624373;
            __m256d  *a3379323;
            double  *a3379320, *a3379321;
            int a3379318, a3379319, a3379322, b133665;
            a3379318 = ((81)*(i1511776));
            a3379319 = ((9)*(i1511778));
            a3379320 = (X1 + a3379318 + a3379319);
            a3379321 = (X2 + a3379318 + a3379319);
            s3336945 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadh_pd(_mm_load_sd(((double  *) a3379320)), ((double  *) a3379321)), 0), _mm_loadh_pd(_mm_load_sd(((double  *) (1 + a3379320))), ((double  *) (1 + a3379321))), 1);
            U2304568 = _mm_loadh_pd(_mm_load_sd(((double  *) (3 + a3379320))), ((double  *) (3 + a3379321)));
            s3336946 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadh_pd(_mm_load_sd(((double  *) (2 + a3379320))), ((double  *) (2 + a3379321))), 0), U2304568, 1);
            U2304569 = _mm_loadh_pd(_mm_load_sd(((double  *) (4 + a3379320))), ((double  *) (4 + a3379321)));
            U2304570 = _mm_loadh_pd(_mm_load_sd(((double  *) (5 + a3379320))), ((double  *) (5 + a3379321)));
            s3336947 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), U2304569, 0), U2304570, 1);
            s3336948 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadh_pd(_mm_load_sd(((double  *) (6 + a3379320))), ((double  *) (6 + a3379321))), 0), _mm_loadh_pd(_mm_load_sd(((double  *) (7 + a3379320))), ((double  *) (7 + a3379321))), 1);
            a3379322 = ((18)*(i1511778));
            b133665 = (((162)*(i1511776)) + a3379322);
            s3336949 = _mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadh_pd(_mm_load_sd(((double  *) (X1 + (((16 + b133665)) / (2))))), ((double  *) (X2 + (((17 + b133665)) / (2))))), 0);
            s3336950 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), U2304568, 0), U2304569, 1);
            t5624339 = _mm256_add_pd(s3336950, s3336948);
            t5624340 = _mm256_sub_pd(s3336945, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624339));
            s3336951 = _mm256_add_pd(s3336945, t5624339);
            *(((__m256d  *) T197204)) = s3336951;
            s3336952 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s3336950, s3336948), _mm256_sub_pd(s3336950, s3336948), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t5624341 = _mm256_add_pd(t5624340, s3336952);
            t5624342 = _mm256_sub_pd(t5624340, s3336952);
            s3336953 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.76604444311897801, 0.76604444311897801, 1.0, 1.0), t5624341), _mm256_mul_pd(_mm256_set_pd((-0.64278760968653936), 0.64278760968653936, 0.0, 0.0), _mm256_shuffle_pd(t5624341, t5624341, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            *((2 + ((__m256d  *) T197204))) = s3336953;
            s3336954 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.17364817766693036, 0.17364817766693036, 1.0, 1.0), t5624342), _mm256_mul_pd(_mm256_set_pd((-0.98480775301220802), 0.98480775301220802, 0.0, 0.0), _mm256_shuffle_pd(t5624342, t5624342, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            *((4 + ((__m256d  *) T197204))) = s3336954;
            s3336955 = _mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadh_pd(_mm_load_sd(((double  *) (X1 + (((4 + b133665)) / (2))))), ((double  *) (X2 + (((5 + b133665)) / (2))))), 0);
            s3336956 = _mm256_insertf128_pd(_mm256_setzero_pd(), U2304570, 0);
            s3336957 = _mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadh_pd(_mm_load_sd(((double  *) (8 + a3379320))), ((double  *) (8 + a3379321))), 0);
            t5624343 = _mm256_add_pd(s3336956, s3336957);
            t5624344 = _mm256_sub_pd(s3336955, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624343));
            s3336958 = _mm256_mul_pd(_mm256_set_pd(0.0, 0.0, 1.0, 1.0), _mm256_add_pd(s3336955, t5624343));
            *((1 + ((__m256d  *) T197204))) = s3336958;
            s3336959 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s3336956, s3336957), _mm256_sub_pd(s3336956, s3336957), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t5624345 = _mm256_add_pd(t5624344, s3336959);
            t5624346 = _mm256_sub_pd(t5624344, s3336959);
            s3336960 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.0, 0.0, 0.17364817766693036, 0.17364817766693036), t5624345), _mm256_mul_pd(_mm256_set_pd(0.0, 0.0, (-0.98480775301220802), 0.98480775301220802), _mm256_shuffle_pd(t5624345, t5624345, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            *((3 + ((__m256d  *) T197204))) = s3336960;
            s3336961 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.0, 0.0, (-0.93969262078590843), (-0.93969262078590843)), t5624346), _mm256_mul_pd(_mm256_set_pd(0.0, 0.0, (-0.34202014332566871), 0.34202014332566871), _mm256_shuffle_pd(t5624346, t5624346, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            *((5 + ((__m256d  *) T197204))) = s3336961;
            s3336962 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd(((double  *) T197204)), 0), _mm_loadu_pd(((double  *) (8 + ((double  *) T197204)))), 1);
            s3336963 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd(((double  *) (2 + ((double  *) T197204)))), 0), _mm_loadu_pd(((double  *) (10 + ((double  *) T197204)))), 1);
            s3336964 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd(((double  *) (4 + ((double  *) T197204)))), 0), _mm_loadu_pd(((double  *) (12 + ((double  *) T197204)))), 1);
            t5624347 = _mm256_add_pd(s3336963, s3336964);
            t5624348 = _mm256_add_pd(s3336962, t5624347);
            t5624349 = _mm256_sub_pd(s3336962, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624347));
            s3336965 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.10441029119843427, 0.10441029119843427, 0.1111111111111111, 0.1111111111111111), t5624348), _mm256_mul_pd(_mm256_set_pd(0.038002238147296523, (-0.038002238147296523), 0.0, 0.0), _mm256_shuffle_pd(t5624348, t5624348, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s3336966 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s3336963, s3336964), _mm256_sub_pd(s3336963, s3336964), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t5624350 = _mm256_add_pd(t5624349, s3336966);
            t5624351 = _mm256_sub_pd(t5624349, s3336966);
            s3336967 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.019294241962992262, 0.019294241962992262, 0.055555555555555552, 0.055555555555555552), t5624350), _mm256_mul_pd(_mm256_set_pd(0.10942308366802311, (-0.10942308366802311), 0.096225044864937617, (-0.096225044864937617)), _mm256_shuffle_pd(t5624350, t5624350, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s3336968 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.085116049235441998, 0.085116049235441998, 0.055555555555555552, 0.055555555555555552), t5624351), _mm256_mul_pd(_mm256_set_pd((-0.071420845520726597), 0.071420845520726597, (-0.096225044864937617), 0.096225044864937617), _mm256_shuffle_pd(t5624351, t5624351, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s3336969 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd(((double  *) (16 + ((double  *) T197204)))), 0), _mm_loadu_pd(((double  *) (24 + ((double  *) T197204)))), 1);
            s3336970 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd(((double  *) (18 + ((double  *) T197204)))), 0), _mm_loadu_pd(((double  *) (26 + ((double  *) T197204)))), 1);
            s3336971 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd(((double  *) (20 + ((double  *) T197204)))), 0), _mm_loadu_pd(((double  *) (28 + ((double  *) T197204)))), 1);
            t5624352 = _mm256_add_pd(s3336970, s3336971);
            t5624353 = _mm256_add_pd(s3336969, t5624352);
            t5624354 = _mm256_sub_pd(s3336969, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624352));
            s3336972 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.0, 0.0, 0.085116049235441998, 0.085116049235441998), t5624353), _mm256_mul_pd(_mm256_set_pd(0.0, 0.0, 0.071420845520726597, (-0.071420845520726597)), _mm256_shuffle_pd(t5624353, t5624353, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s3336973 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s3336970, s3336971), _mm256_sub_pd(s3336970, s3336971), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t5624355 = _mm256_add_pd(t5624354, s3336973);
            t5624356 = _mm256_sub_pd(t5624354, s3336973);
            s3336974 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.0, 0.0, 0.019294241962992262, 0.019294241962992262), t5624355), _mm256_mul_pd(_mm256_set_pd(0.0, 0.0, (-0.10942308366802311), 0.10942308366802311), _mm256_shuffle_pd(t5624355, t5624355, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s3336975 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.0, 0.0, 0.10441029119843427, 0.10441029119843427), t5624356), _mm256_mul_pd(_mm256_set_pd(0.0, 0.0, (-0.038002238147296523), 0.038002238147296523), _mm256_shuffle_pd(t5624356, t5624356, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t5624357 = _mm256_add_pd(s3336967, s3336968);
            s3336976 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s3336967, s3336968), _mm256_sub_pd(s3336967, s3336968), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t5624358 = _mm256_add_pd(s3336965, t5624357);
            t5624359 = _mm256_sub_pd(s3336965, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624357));
            _mm_storeu_pd(((double  *) T197203), _mm256_extractf128_pd(t5624358, 0));
            _mm_storeu_pd(((double  *) (8 + ((double  *) T197203))), _mm256_extractf128_pd(t5624358, 1));
            t5624360 = _mm256_add_pd(t5624359, s3336976);
            t5624361 = _mm256_sub_pd(t5624359, s3336976);
            _mm_storeu_pd(((double  *) (2 + ((double  *) T197203))), _mm256_extractf128_pd(t5624360, 0));
            _mm_storeu_pd(((double  *) (10 + ((double  *) T197203))), _mm256_extractf128_pd(t5624360, 1));
            _mm_storeu_pd(((double  *) (4 + ((double  *) T197203))), _mm256_extractf128_pd(t5624361, 0));
            _mm_storeu_pd(((double  *) (12 + ((double  *) T197203))), _mm256_extractf128_pd(t5624361, 1));
            t5624362 = _mm256_add_pd(s3336974, s3336975);
            s3336977 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s3336974, s3336975), _mm256_sub_pd(s3336974, s3336975), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t5624363 = _mm256_add_pd(s3336972, t5624362);
            t5624364 = _mm256_sub_pd(s3336972, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624362));
            _mm_storeu_pd(((double  *) (16 + ((double  *) T197203))), _mm256_extractf128_pd(t5624363, 0));
            _mm_storeu_pd(((double  *) (24 + ((double  *) T197203))), _mm256_extractf128_pd(t5624363, 1));
            t5624365 = _mm256_add_pd(t5624364, s3336977);
            t5624366 = _mm256_sub_pd(t5624364, s3336977);
            _mm_storeu_pd(((double  *) (18 + ((double  *) T197203))), _mm256_extractf128_pd(t5624365, 0));
            _mm_storeu_pd(((double  *) (26 + ((double  *) T197203))), _mm256_extractf128_pd(t5624365, 1));
            _mm_storeu_pd(((double  *) (20 + ((double  *) T197203))), _mm256_extractf128_pd(t5624366, 0));
            _mm_storeu_pd(((double  *) (28 + ((double  *) T197203))), _mm256_extractf128_pd(t5624366, 1));
            s3336978 = *(((__m256d  *) T197203));
            s3336979 = *((2 + ((__m256d  *) T197203)));
            s3336980 = *((4 + ((__m256d  *) T197203)));
            s3336981 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.76604444311897801, 0.76604444311897801, 1.0, 1.0), s3336979), _mm256_mul_pd(_mm256_set_pd(0.64278760968653936, (-0.64278760968653936), 0.0, 0.0), _mm256_shuffle_pd(s3336979, s3336979, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s3336982 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.17364817766693036, 0.17364817766693036, 1.0, 1.0), s3336980), _mm256_mul_pd(_mm256_set_pd(0.98480775301220802, (-0.98480775301220802), 0.0, 0.0), _mm256_shuffle_pd(s3336980, s3336980, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t5624367 = _mm256_add_pd(s3336981, s3336982);
            s3336983 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s3336981, s3336982), _mm256_sub_pd(s3336981, s3336982), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t5624368 = _mm256_add_pd(s3336978, t5624367);
            t5624369 = _mm256_sub_pd(s3336978, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624367));
            U2304571 = _mm256_extractf128_pd(t5624368, 0);
            _mm_storel_pd(((double  *) T197202), U2304571);
            _mm_storeh_pd(((double  *) (1 + ((double  *) T197202))), U2304571);
            U2304572 = _mm256_extractf128_pd(t5624368, 1);
            _mm_storel_pd(((double  *) (2 + ((double  *) T197202))), U2304572);
            _mm_storeh_pd(((double  *) (3 + ((double  *) T197202))), U2304572);
            t5624370 = _mm256_add_pd(t5624369, s3336983);
            t5624371 = _mm256_sub_pd(t5624369, s3336983);
            U2304573 = _mm256_extractf128_pd(t5624370, 0);
            _mm_storel_pd(((double  *) (6 + ((double  *) T197202))), U2304573);
            _mm_storeh_pd(((double  *) (7 + ((double  *) T197202))), U2304573);
            U2304574 = _mm256_extractf128_pd(t5624370, 1);
            _mm_storel_pd(((double  *) (8 + ((double  *) T197202))), U2304574);
            _mm_storeh_pd(((double  *) (9 + ((double  *) T197202))), U2304574);
            U2304575 = _mm256_extractf128_pd(t5624371, 0);
            _mm_storel_pd(((double  *) (12 + ((double  *) T197202))), U2304575);
            _mm_storeh_pd(((double  *) (13 + ((double  *) T197202))), U2304575);
            U2304576 = _mm256_extractf128_pd(t5624371, 1);
            _mm_storel_pd(((double  *) (14 + ((double  *) T197202))), U2304576);
            _mm_storeh_pd(((double  *) (15 + ((double  *) T197202))), U2304576);
            s3336984 = _mm256_mul_pd(_mm256_set_pd(0.0, 0.0, 1.0, 1.0), *((1 + ((__m256d  *) T197203))));
            s3336985 = *((3 + ((__m256d  *) T197203)));
            s3336986 = *((5 + ((__m256d  *) T197203)));
            s3336987 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.0, 0.0, 0.17364817766693036, 0.17364817766693036), s3336985), _mm256_mul_pd(_mm256_set_pd(0.0, 0.0, 0.98480775301220802, (-0.98480775301220802)), _mm256_shuffle_pd(s3336985, s3336985, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s3336988 = _mm256_add_pd(_mm256_mul_pd(_mm256_set_pd(0.0, 0.0, (-0.93969262078590843), (-0.93969262078590843)), s3336986), _mm256_mul_pd(_mm256_set_pd(0.0, 0.0, 0.34202014332566871, (-0.34202014332566871)), _mm256_shuffle_pd(s3336986, s3336986, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t5624372 = _mm256_add_pd(s3336987, s3336988);
            s3336989 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s3336987, s3336988), _mm256_sub_pd(s3336987, s3336988), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t5624373 = _mm256_sub_pd(s3336984, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624372));
            U2304577 = _mm256_extractf128_pd(_mm256_add_pd(s3336984, t5624372), 0);
            _mm_storel_pd(((double  *) (4 + ((double  *) T197202))), U2304577);
            _mm_storeh_pd(((double  *) (5 + ((double  *) T197202))), U2304577);
            U2304578 = _mm256_extractf128_pd(_mm256_add_pd(t5624373, s3336989), 0);
            _mm_storel_pd(((double  *) (10 + ((double  *) T197202))), U2304578);
            _mm_storeh_pd(((double  *) (11 + ((double  *) T197202))), U2304578);
            U2304579 = _mm256_extractf128_pd(_mm256_sub_pd(t5624373, s3336989), 0);
            _mm_storel_pd(((double  *) (16 + ((double  *) T197202))), U2304579);
            _mm_storeh_pd(((double  *) (17 + ((double  *) T197202))), U2304579);
            s3336990 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd(((double  *) T197202)), 0), _mm_loadu_pd(((double  *) (2 + ((double  *) T197202)))), 1);
            s3336991 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd(((double  *) (4 + ((double  *) T197202)))), 0), _mm_loadu_pd(((double  *) (6 + ((double  *) T197202)))), 1);
            s3336992 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd(((double  *) (8 + ((double  *) T197202)))), 0), _mm_loadu_pd(((double  *) (10 + ((double  *) T197202)))), 1);
            s3336993 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd(((double  *) (12 + ((double  *) T197202)))), 0), _mm_loadu_pd(((double  *) (14 + ((double  *) T197202)))), 1);
            s3336994 = _mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadu_pd(((double  *) (16 + ((double  *) T197202)))), 0);
            a3379323 = ((__m256d  *) T197198);
            s3336995 = _mm256_permute2f128_pd(s3336945, s3336990, (0) | ((2) << 4));
            *((a3379323 + a3379322)) = s3336995;
            s3336996 = _mm256_permute2f128_pd(s3336945, s3336990, (1) | ((3) << 4));
            *((1 + a3379323 + a3379322)) = s3336996;
            s3336997 = _mm256_permute2f128_pd(s3336946, s3336991, (0) | ((2) << 4));
            *((2 + a3379323 + a3379322)) = s3336997;
            s3336998 = _mm256_permute2f128_pd(s3336946, s3336991, (1) | ((3) << 4));
            *((3 + a3379323 + a3379322)) = s3336998;
            s3336999 = _mm256_permute2f128_pd(s3336947, s3336992, (0) | ((2) << 4));
            *((4 + a3379323 + a3379322)) = s3336999;
            s3337000 = _mm256_permute2f128_pd(s3336947, s3336992, (1) | ((3) << 4));
            *((5 + a3379323 + a3379322)) = s3337000;
            s3337001 = _mm256_permute2f128_pd(s3336948, s3336993, (0) | ((2) << 4));
            *((6 + a3379323 + a3379322)) = s3337001;
            s3337002 = _mm256_permute2f128_pd(s3336948, s3336993, (1) | ((3) << 4));
            *((7 + a3379323 + a3379322)) = s3337002;
            s3337003 = _mm256_permute2f128_pd(s3336949, s3336994, (0) | ((2) << 4));
            *((8 + a3379323 + a3379322)) = s3337003;
            s3337004 = _mm256_permute2f128_pd(s3336949, s3336994, (1) | ((3) << 4));
            *((9 + a3379323 + a3379322)) = s3337004;
        }
        for(int i1511779 = 0; i1511779 <= 8; i1511779++) {
            __m128d U2304767, U2304768, U2304769, U2304770, U2304771, U2304772, U2304773, U2304774
    , U2304775, U2304776, U2304777, U2304778, U2304779, U2304780, U2304781, U2304782
    , U2304783, U2304784, U2304785, U2304786, U2304787, U2304788, U2304789, U2304790
    , U2304791, U2304792, U2304793, U2304794, U2304795, U2304796, U2304797, U2304798
    , U2304799, U2304800, U2304801, U2304802;
            __m256d s3337119, s3337120, s3337121, s3337122, s3337123, s3337124, s3337125, s3337126
    , s3337127, s3337128, s3337129, s3337130, s3337131, s3337132, s3337133, s3337134
    , s3337135, s3337136, s3337137, s3337138, s3337139, s3337140, s3337141, s3337142
    , s3337143, s3337144, s3337145, s3337146, s3337147, s3337148, s3337149, s3337150
    , s3337151, s3337152, s3337153, s3337154, s3337155, s3337156, t5624577, t5624578
    , t5624579, t5624580, t5624581, t5624582, t5624583, t5624584, t5624585, t5624586
    , t5624587, t5624588, t5624589, t5624590, t5624591, t5624592, t5624593, t5624594
    , t5624595, t5624596, t5624597, t5624598, t5624599, t5624600, t5624601, t5624602
    , t5624603, t5624604, t5624605, t5624606, t5624607, t5624608, t5624609, t5624610
    , t5624611, t5624612, t5624613, t5624614, t5624615, t5624616, t5624617, t5624618
    , t5624619, t5624620, t5624621, t5624622, t5624623, t5624624, t5624625, t5624626
    , t5624627, t5624628, t5624629, t5624630, t5624631, t5624632, t5624633, t5624634
    , t5624635;
            __m256d  *a3379877;
            double  *a3379880, *a3379881;
            int a3379878, a3379879;
            a3379877 = ((__m256d  *) T197198);
            s3337119 = *((a3379877 + i1511779));
            s3337120 = *((18 + a3379877 + i1511779));
            s3337121 = *((36 + a3379877 + i1511779));
            s3337122 = *((54 + a3379877 + i1511779));
            s3337123 = *((72 + a3379877 + i1511779));
            s3337124 = *((90 + a3379877 + i1511779));
            s3337125 = *((108 + a3379877 + i1511779));
            s3337126 = *((126 + a3379877 + i1511779));
            s3337127 = *((144 + a3379877 + i1511779));
            U2304767 = _mm256_extractf128_pd(s3337119, 0);
            a3379878 = ((648)*(i1511776));
            a3379879 = ((2)*(i1511779));
            a3379880 = (Y1 + a3379878 + a3379879);
            _mm_storel_pd(((double  *) a3379880), U2304767);
            a3379881 = (Y2 + a3379878 + a3379879);
            _mm_storeh_pd(((double  *) a3379881), U2304767);
            U2304768 = _mm256_extractf128_pd(s3337119, 1);
            _mm_storel_pd(((double  *) (1 + a3379880)), U2304768);
            _mm_storeh_pd(((double  *) (1 + a3379881)), U2304768);
            U2304769 = _mm256_extractf128_pd(s3337120, 0);
            _mm_storel_pd(((double  *) (36 + a3379880)), U2304769);
            _mm_storeh_pd(((double  *) (36 + a3379881)), U2304769);
            U2304770 = _mm256_extractf128_pd(s3337120, 1);
            _mm_storel_pd(((double  *) (37 + a3379880)), U2304770);
            _mm_storeh_pd(((double  *) (37 + a3379881)), U2304770);
            U2304771 = _mm256_extractf128_pd(s3337121, 0);
            _mm_storel_pd(((double  *) (72 + a3379880)), U2304771);
            _mm_storeh_pd(((double  *) (72 + a3379881)), U2304771);
            U2304772 = _mm256_extractf128_pd(s3337121, 1);
            _mm_storel_pd(((double  *) (73 + a3379880)), U2304772);
            _mm_storeh_pd(((double  *) (73 + a3379881)), U2304772);
            U2304773 = _mm256_extractf128_pd(s3337122, 0);
            _mm_storel_pd(((double  *) (108 + a3379880)), U2304773);
            _mm_storeh_pd(((double  *) (108 + a3379881)), U2304773);
            U2304774 = _mm256_extractf128_pd(s3337122, 1);
            _mm_storel_pd(((double  *) (109 + a3379880)), U2304774);
            _mm_storeh_pd(((double  *) (109 + a3379881)), U2304774);
            U2304775 = _mm256_extractf128_pd(s3337123, 0);
            _mm_storel_pd(((double  *) (144 + a3379880)), U2304775);
            _mm_storeh_pd(((double  *) (144 + a3379881)), U2304775);
            U2304776 = _mm256_extractf128_pd(s3337123, 1);
            _mm_storel_pd(((double  *) (145 + a3379880)), U2304776);
            _mm_storeh_pd(((double  *) (145 + a3379881)), U2304776);
            U2304777 = _mm256_extractf128_pd(s3337124, 0);
            _mm_storel_pd(((double  *) (180 + a3379880)), U2304777);
            _mm_storeh_pd(((double  *) (180 + a3379881)), U2304777);
            U2304778 = _mm256_extractf128_pd(s3337124, 1);
            _mm_storel_pd(((double  *) (181 + a3379880)), U2304778);
            _mm_storeh_pd(((double  *) (181 + a3379881)), U2304778);
            U2304779 = _mm256_extractf128_pd(s3337125, 0);
            _mm_storel_pd(((double  *) (216 + a3379880)), U2304779);
            _mm_storeh_pd(((double  *) (216 + a3379881)), U2304779);
            U2304780 = _mm256_extractf128_pd(s3337125, 1);
            _mm_storel_pd(((double  *) (217 + a3379880)), U2304780);
            _mm_storeh_pd(((double  *) (217 + a3379881)), U2304780);
            U2304781 = _mm256_extractf128_pd(s3337126, 0);
            _mm_storel_pd(((double  *) (252 + a3379880)), U2304781);
            _mm_storeh_pd(((double  *) (252 + a3379881)), U2304781);
            U2304782 = _mm256_extractf128_pd(s3337126, 1);
            _mm_storel_pd(((double  *) (253 + a3379880)), U2304782);
            _mm_storeh_pd(((double  *) (253 + a3379881)), U2304782);
            U2304783 = _mm256_extractf128_pd(s3337127, 0);
            _mm_storel_pd(((double  *) (288 + a3379880)), U2304783);
            _mm_storeh_pd(((double  *) (288 + a3379881)), U2304783);
            U2304784 = _mm256_extractf128_pd(s3337127, 1);
            _mm_storel_pd(((double  *) (289 + a3379880)), U2304784);
            _mm_storeh_pd(((double  *) (289 + a3379881)), U2304784);
            t5624577 = _mm256_add_pd(s3337122, s3337125);
            s3337128 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s3337122, s3337125), _mm256_sub_pd(s3337122, s3337125), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t5624578 = _mm256_add_pd(s3337119, t5624577);
            t5624579 = _mm256_sub_pd(s3337119, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624577));
            t5624580 = _mm256_add_pd(t5624579, s3337128);
            t5624581 = _mm256_sub_pd(t5624579, s3337128);
            t5624582 = _mm256_add_pd(s3337123, s3337126);
            s3337129 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s3337123, s3337126), _mm256_sub_pd(s3337123, s3337126), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t5624583 = _mm256_add_pd(s3337120, t5624582);
            t5624584 = _mm256_sub_pd(s3337120, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624582));
            t5624585 = _mm256_add_pd(t5624584, s3337129);
            t5624586 = _mm256_sub_pd(t5624584, s3337129);
            s3337130 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.76604444311897801), t5624585), _mm256_mul_pd(_mm256_set_pd((-0.64278760968653936), 0.64278760968653936, (-0.64278760968653936), 0.64278760968653936), _mm256_shuffle_pd(t5624585, t5624585, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s3337131 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.17364817766693036), t5624586), _mm256_mul_pd(_mm256_set_pd((-0.98480775301220802), 0.98480775301220802, (-0.98480775301220802), 0.98480775301220802), _mm256_shuffle_pd(t5624586, t5624586, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t5624587 = _mm256_add_pd(s3337124, s3337127);
            s3337132 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s3337124, s3337127), _mm256_sub_pd(s3337124, s3337127), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t5624588 = _mm256_add_pd(s3337121, t5624587);
            t5624589 = _mm256_sub_pd(s3337121, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624587));
            t5624590 = _mm256_add_pd(t5624589, s3337132);
            t5624591 = _mm256_sub_pd(t5624589, s3337132);
            s3337133 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.17364817766693036), t5624590), _mm256_mul_pd(_mm256_set_pd((-0.98480775301220802), 0.98480775301220802, (-0.98480775301220802), 0.98480775301220802), _mm256_shuffle_pd(t5624590, t5624590, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s3337134 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd((-0.93969262078590843)), t5624591), _mm256_mul_pd(_mm256_set_pd((-0.34202014332566871), 0.34202014332566871, (-0.34202014332566871), 0.34202014332566871), _mm256_shuffle_pd(t5624591, t5624591, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t5624592 = _mm256_add_pd(t5624583, t5624588);
            s3337135 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(t5624583, t5624588), _mm256_sub_pd(t5624583, t5624588), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t5624593 = _mm256_sub_pd(t5624578, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624592));
            s3337136 = _mm256_mul_pd(_mm256_set1_pd(0.1111111111111111), _mm256_add_pd(t5624578, t5624592));
            t5624594 = _mm256_add_pd(t5624593, s3337135);
            t5624595 = _mm256_sub_pd(t5624593, s3337135);
            s3337137 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.055555555555555552), t5624594), _mm256_mul_pd(_mm256_set_pd(0.096225044864937617, (-0.096225044864937617), 0.096225044864937617, (-0.096225044864937617)), _mm256_shuffle_pd(t5624594, t5624594, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s3337138 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.055555555555555552), t5624595), _mm256_mul_pd(_mm256_set_pd((-0.096225044864937617), 0.096225044864937617, (-0.096225044864937617), 0.096225044864937617), _mm256_shuffle_pd(t5624595, t5624595, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t5624596 = _mm256_add_pd(s3337130, s3337133);
            s3337139 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s3337130, s3337133), _mm256_sub_pd(s3337130, s3337133), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t5624597 = _mm256_add_pd(t5624580, t5624596);
            t5624598 = _mm256_sub_pd(t5624580, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624596));
            s3337140 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.10441029119843427), t5624597), _mm256_mul_pd(_mm256_set_pd(0.038002238147296523, (-0.038002238147296523), 0.038002238147296523, (-0.038002238147296523)), _mm256_shuffle_pd(t5624597, t5624597, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t5624599 = _mm256_add_pd(t5624598, s3337139);
            t5624600 = _mm256_sub_pd(t5624598, s3337139);
            s3337141 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.019294241962992262), t5624599), _mm256_mul_pd(_mm256_set_pd(0.10942308366802311, (-0.10942308366802311), 0.10942308366802311, (-0.10942308366802311)), _mm256_shuffle_pd(t5624599, t5624599, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s3337142 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.085116049235441998), t5624600), _mm256_mul_pd(_mm256_set_pd((-0.071420845520726597), 0.071420845520726597, (-0.071420845520726597), 0.071420845520726597), _mm256_shuffle_pd(t5624600, t5624600, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t5624601 = _mm256_add_pd(s3337131, s3337134);
            s3337143 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s3337131, s3337134), _mm256_sub_pd(s3337131, s3337134), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t5624602 = _mm256_add_pd(t5624581, t5624601);
            t5624603 = _mm256_sub_pd(t5624581, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624601));
            s3337144 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.085116049235441998), t5624602), _mm256_mul_pd(_mm256_set_pd(0.071420845520726597, (-0.071420845520726597), 0.071420845520726597, (-0.071420845520726597)), _mm256_shuffle_pd(t5624602, t5624602, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t5624604 = _mm256_add_pd(t5624603, s3337143);
            t5624605 = _mm256_sub_pd(t5624603, s3337143);
            s3337145 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.019294241962992262), t5624604), _mm256_mul_pd(_mm256_set_pd((-0.10942308366802311), 0.10942308366802311, (-0.10942308366802311), 0.10942308366802311), _mm256_shuffle_pd(t5624604, t5624604, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s3337146 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.10441029119843427), t5624605), _mm256_mul_pd(_mm256_set_pd((-0.038002238147296523), 0.038002238147296523, (-0.038002238147296523), 0.038002238147296523), _mm256_shuffle_pd(t5624605, t5624605, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t5624606 = _mm256_add_pd(s3337137, s3337138);
            s3337147 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s3337137, s3337138), _mm256_sub_pd(s3337137, s3337138), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t5624607 = _mm256_add_pd(s3337136, t5624606);
            t5624608 = _mm256_sub_pd(s3337136, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624606));
            t5624609 = _mm256_add_pd(t5624608, s3337147);
            t5624610 = _mm256_sub_pd(t5624608, s3337147);
            t5624611 = _mm256_add_pd(s3337141, s3337142);
            s3337148 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s3337141, s3337142), _mm256_sub_pd(s3337141, s3337142), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t5624612 = _mm256_add_pd(s3337140, t5624611);
            t5624613 = _mm256_sub_pd(s3337140, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624611));
            t5624614 = _mm256_add_pd(t5624613, s3337148);
            t5624615 = _mm256_sub_pd(t5624613, s3337148);
            s3337149 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.76604444311897801), t5624614), _mm256_mul_pd(_mm256_set_pd(0.64278760968653936, (-0.64278760968653936), 0.64278760968653936, (-0.64278760968653936)), _mm256_shuffle_pd(t5624614, t5624614, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s3337150 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.17364817766693036), t5624615), _mm256_mul_pd(_mm256_set_pd(0.98480775301220802, (-0.98480775301220802), 0.98480775301220802, (-0.98480775301220802)), _mm256_shuffle_pd(t5624615, t5624615, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t5624616 = _mm256_add_pd(s3337145, s3337146);
            s3337151 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s3337145, s3337146), _mm256_sub_pd(s3337145, s3337146), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t5624617 = _mm256_add_pd(s3337144, t5624616);
            t5624618 = _mm256_sub_pd(s3337144, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624616));
            t5624619 = _mm256_add_pd(t5624618, s3337151);
            t5624620 = _mm256_sub_pd(t5624618, s3337151);
            s3337152 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.17364817766693036), t5624619), _mm256_mul_pd(_mm256_set_pd(0.98480775301220802, (-0.98480775301220802), 0.98480775301220802, (-0.98480775301220802)), _mm256_shuffle_pd(t5624619, t5624619, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            s3337153 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd((-0.93969262078590843)), t5624620), _mm256_mul_pd(_mm256_set_pd(0.34202014332566871, (-0.34202014332566871), 0.34202014332566871, (-0.34202014332566871)), _mm256_shuffle_pd(t5624620, t5624620, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
            t5624621 = _mm256_add_pd(t5624612, t5624617);
            s3337154 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(t5624612, t5624617), _mm256_sub_pd(t5624612, t5624617), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t5624622 = _mm256_add_pd(t5624607, t5624621);
            t5624623 = _mm256_sub_pd(t5624607, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624621));
            U2304785 = _mm256_extractf128_pd(t5624622, 0);
            _mm_storel_pd(((double  *) (18 + a3379880)), U2304785);
            _mm_storeh_pd(((double  *) (18 + a3379881)), U2304785);
            U2304786 = _mm256_extractf128_pd(t5624622, 1);
            _mm_storel_pd(((double  *) (19 + a3379880)), U2304786);
            _mm_storeh_pd(((double  *) (19 + a3379881)), U2304786);
            t5624624 = _mm256_add_pd(t5624623, s3337154);
            t5624625 = _mm256_sub_pd(t5624623, s3337154);
            U2304787 = _mm256_extractf128_pd(t5624624, 0);
            _mm_storel_pd(((double  *) (126 + a3379880)), U2304787);
            _mm_storeh_pd(((double  *) (126 + a3379881)), U2304787);
            U2304788 = _mm256_extractf128_pd(t5624624, 1);
            _mm_storel_pd(((double  *) (127 + a3379880)), U2304788);
            _mm_storeh_pd(((double  *) (127 + a3379881)), U2304788);
            U2304789 = _mm256_extractf128_pd(t5624625, 0);
            _mm_storel_pd(((double  *) (234 + a3379880)), U2304789);
            _mm_storeh_pd(((double  *) (234 + a3379881)), U2304789);
            U2304790 = _mm256_extractf128_pd(t5624625, 1);
            _mm_storel_pd(((double  *) (235 + a3379880)), U2304790);
            _mm_storeh_pd(((double  *) (235 + a3379881)), U2304790);
            t5624626 = _mm256_add_pd(s3337149, s3337152);
            s3337155 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s3337149, s3337152), _mm256_sub_pd(s3337149, s3337152), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t5624627 = _mm256_add_pd(t5624609, t5624626);
            t5624628 = _mm256_sub_pd(t5624609, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624626));
            U2304791 = _mm256_extractf128_pd(t5624627, 0);
            _mm_storel_pd(((double  *) (54 + a3379880)), U2304791);
            _mm_storeh_pd(((double  *) (54 + a3379881)), U2304791);
            U2304792 = _mm256_extractf128_pd(t5624627, 1);
            _mm_storel_pd(((double  *) (55 + a3379880)), U2304792);
            _mm_storeh_pd(((double  *) (55 + a3379881)), U2304792);
            t5624629 = _mm256_add_pd(t5624628, s3337155);
            t5624630 = _mm256_sub_pd(t5624628, s3337155);
            U2304793 = _mm256_extractf128_pd(t5624629, 0);
            _mm_storel_pd(((double  *) (162 + a3379880)), U2304793);
            _mm_storeh_pd(((double  *) (162 + a3379881)), U2304793);
            U2304794 = _mm256_extractf128_pd(t5624629, 1);
            _mm_storel_pd(((double  *) (163 + a3379880)), U2304794);
            _mm_storeh_pd(((double  *) (163 + a3379881)), U2304794);
            U2304795 = _mm256_extractf128_pd(t5624630, 0);
            _mm_storel_pd(((double  *) (270 + a3379880)), U2304795);
            _mm_storeh_pd(((double  *) (270 + a3379881)), U2304795);
            U2304796 = _mm256_extractf128_pd(t5624630, 1);
            _mm_storel_pd(((double  *) (271 + a3379880)), U2304796);
            _mm_storeh_pd(((double  *) (271 + a3379881)), U2304796);
            t5624631 = _mm256_add_pd(s3337150, s3337153);
            s3337156 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s3337150, s3337153), _mm256_sub_pd(s3337150, s3337153), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
            t5624632 = _mm256_add_pd(t5624610, t5624631);
            t5624633 = _mm256_sub_pd(t5624610, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624631));
            U2304797 = _mm256_extractf128_pd(t5624632, 0);
            _mm_storel_pd(((double  *) (90 + a3379880)), U2304797);
            _mm_storeh_pd(((double  *) (90 + a3379881)), U2304797);
            U2304798 = _mm256_extractf128_pd(t5624632, 1);
            _mm_storel_pd(((double  *) (91 + a3379880)), U2304798);
            _mm_storeh_pd(((double  *) (91 + a3379881)), U2304798);
            t5624634 = _mm256_add_pd(t5624633, s3337156);
            t5624635 = _mm256_sub_pd(t5624633, s3337156);
            U2304799 = _mm256_extractf128_pd(t5624634, 0);
            _mm_storel_pd(((double  *) (198 + a3379880)), U2304799);
            _mm_storeh_pd(((double  *) (198 + a3379881)), U2304799);
            U2304800 = _mm256_extractf128_pd(t5624634, 1);
            _mm_storel_pd(((double  *) (199 + a3379880)), U2304800);
            _mm_storeh_pd(((double  *) (199 + a3379881)), U2304800);
            U2304801 = _mm256_extractf128_pd(t5624635, 0);
            _mm_storel_pd(((double  *) (306 + a3379880)), U2304801);
            _mm_storeh_pd(((double  *) (306 + a3379881)), U2304801);
            U2304802 = _mm256_extractf128_pd(t5624635, 1);
            _mm_storel_pd(((double  *) (307 + a3379880)), U2304802);
            _mm_storeh_pd(((double  *) (307 + a3379881)), U2304802);
        }
    }
    for(int i1511781 = 0; i1511781 <= 161; i1511781++) {
        __m128d U2305026, U2305027, U2305028, U2305029, U2305030, U2305031, U2305032, U2305033
    , U2305034, U2305035, U2305036, U2305037, U2305038, U2305039, U2305040, U2305041
    , U2305042, U2305043;
        __m256d s3337271, s3337272, s3337273, s3337274, s3337275, s3337276, s3337277, s3337278
    , s3337279, s3337280, s3337281, s3337282, s3337283, s3337284, s3337285, s3337286
    , s3337287, s3337288, s3337289, s3337290, s3337291, s3337292, s3337293, s3337294
    , s3337295, s3337296, s3337297, s3337298, s3337299, s3337300, s3337301, s3337302
    , s3337303, s3337304, s3337305, s3337306, s3337307, s3337308, t5624839, t5624840
    , t5624841, t5624842, t5624843, t5624844, t5624845, t5624846, t5624847, t5624848
    , t5624849, t5624850, t5624851, t5624852, t5624853, t5624854, t5624855, t5624856
    , t5624857, t5624858, t5624859, t5624860, t5624861, t5624862, t5624863, t5624864
    , t5624865, t5624866, t5624867, t5624868, t5624869, t5624870, t5624871, t5624872
    , t5624873, t5624874, t5624875, t5624876, t5624877, t5624878, t5624879, t5624880
    , t5624881, t5624882, t5624883, t5624884, t5624885, t5624886, t5624887, t5624888
    , t5624889, t5624890, t5624891, t5624892, t5624893, t5624894, t5624895, t5624896
    , t5624897;
        double  *a3380337, *b133882;
        int a3380336;
        a3380336 = ((2)*(i1511781));
        a3380337 = (Y2 + a3380336);
        b133882 = (Y1 + a3380336);
        s3337271 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadh_pd(_mm_load_sd(((double  *) (Y1 + ((2)*(i1511781))))), ((double  *) a3380337)), 0), _mm_loadh_pd(_mm_load_sd(((double  *) (1 + b133882))), ((double  *) (1 + a3380337))), 1);
        s3337272 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadh_pd(_mm_load_sd(((double  *) (1944 + b133882))), ((double  *) (1944 + a3380337))), 0), _mm_loadh_pd(_mm_load_sd(((double  *) (1945 + b133882))), ((double  *) (1945 + a3380337))), 1);
        s3337273 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadh_pd(_mm_load_sd(((double  *) (3888 + b133882))), ((double  *) (3888 + a3380337))), 0), _mm_loadh_pd(_mm_load_sd(((double  *) (3889 + b133882))), ((double  *) (3889 + a3380337))), 1);
        t5624839 = _mm256_add_pd(s3337272, s3337273);
        s3337274 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s3337272, s3337273), _mm256_sub_pd(s3337272, s3337273), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t5624840 = _mm256_add_pd(s3337271, t5624839);
        t5624841 = _mm256_sub_pd(s3337271, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624839));
        t5624842 = _mm256_add_pd(t5624841, s3337274);
        t5624843 = _mm256_sub_pd(t5624841, s3337274);
        s3337275 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadh_pd(_mm_load_sd(((double  *) (648 + b133882))), ((double  *) (648 + a3380337))), 0), _mm_loadh_pd(_mm_load_sd(((double  *) (649 + b133882))), ((double  *) (649 + a3380337))), 1);
        s3337276 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadh_pd(_mm_load_sd(((double  *) (2592 + b133882))), ((double  *) (2592 + a3380337))), 0), _mm_loadh_pd(_mm_load_sd(((double  *) (2593 + b133882))), ((double  *) (2593 + a3380337))), 1);
        s3337277 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadh_pd(_mm_load_sd(((double  *) (4536 + b133882))), ((double  *) (4536 + a3380337))), 0), _mm_loadh_pd(_mm_load_sd(((double  *) (4537 + b133882))), ((double  *) (4537 + a3380337))), 1);
        t5624844 = _mm256_add_pd(s3337276, s3337277);
        s3337278 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s3337276, s3337277), _mm256_sub_pd(s3337276, s3337277), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t5624845 = _mm256_add_pd(s3337275, t5624844);
        t5624846 = _mm256_sub_pd(s3337275, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624844));
        t5624847 = _mm256_add_pd(t5624846, s3337278);
        t5624848 = _mm256_sub_pd(t5624846, s3337278);
        s3337279 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.76604444311897801), t5624847), _mm256_mul_pd(_mm256_set_pd((-0.64278760968653936), 0.64278760968653936, (-0.64278760968653936), 0.64278760968653936), _mm256_shuffle_pd(t5624847, t5624847, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        s3337280 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.17364817766693036), t5624848), _mm256_mul_pd(_mm256_set_pd((-0.98480775301220802), 0.98480775301220802, (-0.98480775301220802), 0.98480775301220802), _mm256_shuffle_pd(t5624848, t5624848, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        s3337281 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadh_pd(_mm_load_sd(((double  *) (1296 + b133882))), ((double  *) (1296 + a3380337))), 0), _mm_loadh_pd(_mm_load_sd(((double  *) (1297 + b133882))), ((double  *) (1297 + a3380337))), 1);
        s3337282 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadh_pd(_mm_load_sd(((double  *) (3240 + b133882))), ((double  *) (3240 + a3380337))), 0), _mm_loadh_pd(_mm_load_sd(((double  *) (3241 + b133882))), ((double  *) (3241 + a3380337))), 1);
        s3337283 = _mm256_insertf128_pd(_mm256_insertf128_pd(_mm256_setzero_pd(), _mm_loadh_pd(_mm_load_sd(((double  *) (5184 + b133882))), ((double  *) (5184 + a3380337))), 0), _mm_loadh_pd(_mm_load_sd(((double  *) (5185 + b133882))), ((double  *) (5185 + a3380337))), 1);
        t5624849 = _mm256_add_pd(s3337282, s3337283);
        s3337284 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s3337282, s3337283), _mm256_sub_pd(s3337282, s3337283), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t5624850 = _mm256_add_pd(s3337281, t5624849);
        t5624851 = _mm256_sub_pd(s3337281, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624849));
        t5624852 = _mm256_add_pd(t5624851, s3337284);
        t5624853 = _mm256_sub_pd(t5624851, s3337284);
        s3337285 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.17364817766693036), t5624852), _mm256_mul_pd(_mm256_set_pd((-0.98480775301220802), 0.98480775301220802, (-0.98480775301220802), 0.98480775301220802), _mm256_shuffle_pd(t5624852, t5624852, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        s3337286 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd((-0.93969262078590843)), t5624853), _mm256_mul_pd(_mm256_set_pd((-0.34202014332566871), 0.34202014332566871, (-0.34202014332566871), 0.34202014332566871), _mm256_shuffle_pd(t5624853, t5624853, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        t5624854 = _mm256_add_pd(t5624845, t5624850);
        s3337287 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(t5624845, t5624850), _mm256_sub_pd(t5624845, t5624850), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t5624855 = _mm256_sub_pd(t5624840, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624854));
        s3337288 = _mm256_mul_pd(_mm256_set1_pd(0.1111111111111111), _mm256_add_pd(t5624840, t5624854));
        t5624856 = _mm256_add_pd(t5624855, s3337287);
        t5624857 = _mm256_sub_pd(t5624855, s3337287);
        s3337289 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.055555555555555552), t5624856), _mm256_mul_pd(_mm256_set_pd(0.096225044864937617, (-0.096225044864937617), 0.096225044864937617, (-0.096225044864937617)), _mm256_shuffle_pd(t5624856, t5624856, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        s3337290 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.055555555555555552), t5624857), _mm256_mul_pd(_mm256_set_pd((-0.096225044864937617), 0.096225044864937617, (-0.096225044864937617), 0.096225044864937617), _mm256_shuffle_pd(t5624857, t5624857, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        t5624858 = _mm256_add_pd(s3337279, s3337285);
        s3337291 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s3337279, s3337285), _mm256_sub_pd(s3337279, s3337285), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t5624859 = _mm256_add_pd(t5624842, t5624858);
        t5624860 = _mm256_sub_pd(t5624842, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624858));
        s3337292 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.10441029119843427), t5624859), _mm256_mul_pd(_mm256_set_pd(0.038002238147296523, (-0.038002238147296523), 0.038002238147296523, (-0.038002238147296523)), _mm256_shuffle_pd(t5624859, t5624859, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        t5624861 = _mm256_add_pd(t5624860, s3337291);
        t5624862 = _mm256_sub_pd(t5624860, s3337291);
        s3337293 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.019294241962992262), t5624861), _mm256_mul_pd(_mm256_set_pd(0.10942308366802311, (-0.10942308366802311), 0.10942308366802311, (-0.10942308366802311)), _mm256_shuffle_pd(t5624861, t5624861, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        s3337294 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.085116049235441998), t5624862), _mm256_mul_pd(_mm256_set_pd((-0.071420845520726597), 0.071420845520726597, (-0.071420845520726597), 0.071420845520726597), _mm256_shuffle_pd(t5624862, t5624862, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        t5624863 = _mm256_add_pd(s3337280, s3337286);
        s3337295 = _mm256_mul_pd(_mm256_set_pd((-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386), 0.8660254037844386), _mm256_shuffle_pd(_mm256_sub_pd(s3337280, s3337286), _mm256_sub_pd(s3337280, s3337286), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t5624864 = _mm256_add_pd(t5624843, t5624863);
        t5624865 = _mm256_sub_pd(t5624843, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624863));
        s3337296 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.085116049235441998), t5624864), _mm256_mul_pd(_mm256_set_pd(0.071420845520726597, (-0.071420845520726597), 0.071420845520726597, (-0.071420845520726597)), _mm256_shuffle_pd(t5624864, t5624864, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        t5624866 = _mm256_add_pd(t5624865, s3337295);
        t5624867 = _mm256_sub_pd(t5624865, s3337295);
        s3337297 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.019294241962992262), t5624866), _mm256_mul_pd(_mm256_set_pd((-0.10942308366802311), 0.10942308366802311, (-0.10942308366802311), 0.10942308366802311), _mm256_shuffle_pd(t5624866, t5624866, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        s3337298 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.10441029119843427), t5624867), _mm256_mul_pd(_mm256_set_pd((-0.038002238147296523), 0.038002238147296523, (-0.038002238147296523), 0.038002238147296523), _mm256_shuffle_pd(t5624867, t5624867, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        t5624868 = _mm256_add_pd(s3337289, s3337290);
        s3337299 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s3337289, s3337290), _mm256_sub_pd(s3337289, s3337290), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t5624869 = _mm256_add_pd(s3337288, t5624868);
        t5624870 = _mm256_sub_pd(s3337288, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624868));
        t5624871 = _mm256_add_pd(t5624870, s3337299);
        t5624872 = _mm256_sub_pd(t5624870, s3337299);
        t5624873 = _mm256_add_pd(s3337293, s3337294);
        s3337300 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s3337293, s3337294), _mm256_sub_pd(s3337293, s3337294), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t5624874 = _mm256_add_pd(s3337292, t5624873);
        t5624875 = _mm256_sub_pd(s3337292, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624873));
        t5624876 = _mm256_add_pd(t5624875, s3337300);
        t5624877 = _mm256_sub_pd(t5624875, s3337300);
        s3337301 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.76604444311897801), t5624876), _mm256_mul_pd(_mm256_set_pd(0.64278760968653936, (-0.64278760968653936), 0.64278760968653936, (-0.64278760968653936)), _mm256_shuffle_pd(t5624876, t5624876, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        s3337302 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.17364817766693036), t5624877), _mm256_mul_pd(_mm256_set_pd(0.98480775301220802, (-0.98480775301220802), 0.98480775301220802, (-0.98480775301220802)), _mm256_shuffle_pd(t5624877, t5624877, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        t5624878 = _mm256_add_pd(s3337297, s3337298);
        s3337303 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s3337297, s3337298), _mm256_sub_pd(s3337297, s3337298), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t5624879 = _mm256_add_pd(s3337296, t5624878);
        t5624880 = _mm256_sub_pd(s3337296, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624878));
        t5624881 = _mm256_add_pd(t5624880, s3337303);
        t5624882 = _mm256_sub_pd(t5624880, s3337303);
        s3337304 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd(0.17364817766693036), t5624881), _mm256_mul_pd(_mm256_set_pd(0.98480775301220802, (-0.98480775301220802), 0.98480775301220802, (-0.98480775301220802)), _mm256_shuffle_pd(t5624881, t5624881, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        s3337305 = _mm256_add_pd(_mm256_mul_pd(_mm256_set1_pd((-0.93969262078590843)), t5624882), _mm256_mul_pd(_mm256_set_pd(0.34202014332566871, (-0.34202014332566871), 0.34202014332566871, (-0.34202014332566871)), _mm256_shuffle_pd(t5624882, t5624882, (1) | ((0) << 1) | ((1) << 2) | ((0) << 3))));
        t5624883 = _mm256_add_pd(t5624874, t5624879);
        s3337306 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(t5624874, t5624879), _mm256_sub_pd(t5624874, t5624879), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t5624884 = _mm256_add_pd(t5624869, t5624883);
        t5624885 = _mm256_sub_pd(t5624869, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624883));
        U2305026 = _mm256_extractf128_pd(t5624884, 0);
        _mm_storel_pd(((double  *) (324 + b133882)), U2305026);
        _mm_storeh_pd(((double  *) (324 + a3380337)), U2305026);
        U2305027 = _mm256_extractf128_pd(t5624884, 1);
        _mm_storel_pd(((double  *) (325 + b133882)), U2305027);
        _mm_storeh_pd(((double  *) (325 + a3380337)), U2305027);
        t5624886 = _mm256_add_pd(t5624885, s3337306);
        t5624887 = _mm256_sub_pd(t5624885, s3337306);
        U2305028 = _mm256_extractf128_pd(t5624886, 0);
        _mm_storel_pd(((double  *) (2268 + b133882)), U2305028);
        _mm_storeh_pd(((double  *) (2268 + a3380337)), U2305028);
        U2305029 = _mm256_extractf128_pd(t5624886, 1);
        _mm_storel_pd(((double  *) (2269 + b133882)), U2305029);
        _mm_storeh_pd(((double  *) (2269 + a3380337)), U2305029);
        U2305030 = _mm256_extractf128_pd(t5624887, 0);
        _mm_storel_pd(((double  *) (4212 + b133882)), U2305030);
        _mm_storeh_pd(((double  *) (4212 + a3380337)), U2305030);
        U2305031 = _mm256_extractf128_pd(t5624887, 1);
        _mm_storel_pd(((double  *) (4213 + b133882)), U2305031);
        _mm_storeh_pd(((double  *) (4213 + a3380337)), U2305031);
        t5624888 = _mm256_add_pd(s3337301, s3337304);
        s3337307 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s3337301, s3337304), _mm256_sub_pd(s3337301, s3337304), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t5624889 = _mm256_add_pd(t5624871, t5624888);
        t5624890 = _mm256_sub_pd(t5624871, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624888));
        U2305032 = _mm256_extractf128_pd(t5624889, 0);
        _mm_storel_pd(((double  *) (972 + b133882)), U2305032);
        _mm_storeh_pd(((double  *) (972 + a3380337)), U2305032);
        U2305033 = _mm256_extractf128_pd(t5624889, 1);
        _mm_storel_pd(((double  *) (973 + b133882)), U2305033);
        _mm_storeh_pd(((double  *) (973 + a3380337)), U2305033);
        t5624891 = _mm256_add_pd(t5624890, s3337307);
        t5624892 = _mm256_sub_pd(t5624890, s3337307);
        U2305034 = _mm256_extractf128_pd(t5624891, 0);
        _mm_storel_pd(((double  *) (2916 + b133882)), U2305034);
        _mm_storeh_pd(((double  *) (2916 + a3380337)), U2305034);
        U2305035 = _mm256_extractf128_pd(t5624891, 1);
        _mm_storel_pd(((double  *) (2917 + b133882)), U2305035);
        _mm_storeh_pd(((double  *) (2917 + a3380337)), U2305035);
        U2305036 = _mm256_extractf128_pd(t5624892, 0);
        _mm_storel_pd(((double  *) (4860 + b133882)), U2305036);
        _mm_storeh_pd(((double  *) (4860 + a3380337)), U2305036);
        U2305037 = _mm256_extractf128_pd(t5624892, 1);
        _mm_storel_pd(((double  *) (4861 + b133882)), U2305037);
        _mm_storeh_pd(((double  *) (4861 + a3380337)), U2305037);
        t5624893 = _mm256_add_pd(s3337302, s3337305);
        s3337308 = _mm256_mul_pd(_mm256_set_pd(0.8660254037844386, (-0.8660254037844386), 0.8660254037844386, (-0.8660254037844386)), _mm256_shuffle_pd(_mm256_sub_pd(s3337302, s3337305), _mm256_sub_pd(s3337302, s3337305), (1) | ((0) << 1) | ((1) << 2) | ((0) << 3)));
        t5624894 = _mm256_add_pd(t5624872, t5624893);
        t5624895 = _mm256_sub_pd(t5624872, _mm256_mul_pd(_mm256_set1_pd(0.5), t5624893));
        U2305038 = _mm256_extractf128_pd(t5624894, 0);
        _mm_storel_pd(((double  *) (1620 + b133882)), U2305038);
        _mm_storeh_pd(((double  *) (1620 + a3380337)), U2305038);
        U2305039 = _mm256_extractf128_pd(t5624894, 1);
        _mm_storel_pd(((double  *) (1621 + b133882)), U2305039);
        _mm_storeh_pd(((double  *) (1621 + a3380337)), U2305039);
        t5624896 = _mm256_add_pd(t5624895, s3337308);
        t5624897 = _mm256_sub_pd(t5624895, s3337308);
        U2305040 = _mm256_extractf128_pd(t5624896, 0);
        _mm_storel_pd(((double  *) (3564 + b133882)), U2305040);
        _mm_storeh_pd(((double  *) (3564 + a3380337)), U2305040);
        U2305041 = _mm256_extractf128_pd(t5624896, 1);
        _mm_storel_pd(((double  *) (3565 + b133882)), U2305041);
        _mm_storeh_pd(((double  *) (3565 + a3380337)), U2305041);
        U2305042 = _mm256_extractf128_pd(t5624897, 0);
        _mm_storel_pd(((double  *) (5508 + b133882)), U2305042);
        _mm_storeh_pd(((double  *) (5508 + a3380337)), U2305042);
        U2305043 = _mm256_extractf128_pd(t5624897, 1);
        _mm_storel_pd(((double  *) (5509 + b133882)), U2305043);
        _mm_storeh_pd(((double  *) (5509 + a3380337)), U2305043);
    }
}

void spiral_interpolate_split_CPLX_del_run_9_9_9(void) {
}
